/************************************************************************************
 * This file was auto-generated by CIDEA                           .                *
 * Please do not modify the contents of this file manually.                         *
 ***********************************************************************************/


#include "standardnode.h"
#include "bsp_i2c.h"
#include "cubestar3.h"

uint8_t cubeStar3CommsBuffer[128];

CUBELIB_Result_t CUBESTAR3_ReqAttitudeDataTlm(uint8_t nodeid, CUBESTAR3_AttitudeData_t* attitudeData)
{
    uint8_t tlmId = 177;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    int16_t rawQbar0;
    int16_t rawQbar1;
    int16_t rawQbar2;
    int16_t rawQbar3;
    int16_t rawRightAscension;
    int16_t rawDeclination;
    int16_t rawBSVX;
    int16_t rawBSVY;
    int16_t rawBSVZ;
    I2C_TransferReturn_TypeDef i2cResult;

    if (attitudeData == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 18);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    rawQbar0 = *( (int16_t*) (tlmBuffer + 0) );
    attitudeData->qbar0 = rawQbar0/10000.0;

    rawQbar1 = *( (int16_t*) (tlmBuffer + 2) );
    attitudeData->qbar1 = rawQbar1/10000.0;

    rawQbar2 = *( (int16_t*) (tlmBuffer + 4) );
    attitudeData->qbar2 = rawQbar2/10000.0;

    rawQbar3 = *( (int16_t*) (tlmBuffer + 6) );
    attitudeData->qbar3 = rawQbar3/10000.0;

    rawRightAscension = *( (int16_t*) (tlmBuffer + 8) );
    attitudeData->rightAscension = rawRightAscension/10000.0;

    rawDeclination = *( (int16_t*) (tlmBuffer + 10) );
    attitudeData->declination = rawDeclination/10000.0;

    rawBSVX = *( (int16_t*) (tlmBuffer + 12) );
    attitudeData->bSVX = rawBSVX/10000.0;

    rawBSVY = *( (int16_t*) (tlmBuffer + 14) );
    attitudeData->bSVY = rawBSVY/10000.0;

    rawBSVZ = *( (int16_t*) (tlmBuffer + 16) );
    attitudeData->bSVZ = rawBSVZ/10000.0;

    if ((attitudeData->qbar0 < -1) || (attitudeData->qbar0 > 1))
        return TlmRangeError;

    if ((attitudeData->qbar1 < -1) || (attitudeData->qbar1 > 1))
        return TlmRangeError;

    if ((attitudeData->qbar2 < -1) || (attitudeData->qbar2 > 1))
        return TlmRangeError;

    if ((attitudeData->qbar3 < -1) || (attitudeData->qbar3 > 1))
        return TlmRangeError;

    if ((attitudeData->bSVX < -1) || (attitudeData->bSVX > 1))
        return TlmRangeError;

    if ((attitudeData->bSVY < -1) || (attitudeData->bSVY > 1))
        return TlmRangeError;

    if ((attitudeData->bSVZ < -1) || (attitudeData->bSVZ > 1))
        return TlmRangeError;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqAttitudeTimingTlm(uint8_t nodeid, CUBESTAR3_AttitudeTiming_t* attitudeTiming)
{
    uint8_t tlmId = 166;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (attitudeTiming == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 4);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    attitudeTiming->latestTime = *( (uint16_t*) (tlmBuffer + 0) );

    attitudeTiming->maxTime = *( (uint16_t*) (tlmBuffer + 2) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqBestStarIndexTlm(uint8_t nodeid, CUBESTAR3_BestStarIndex_t* bestStarIndex)
{
    uint8_t tlmId = 169;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (bestStarIndex == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 3);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    bestStarIndex->star1Index = *( (uint8_t*) (tlmBuffer + 0) );

    bestStarIndex->star2Index = *( (uint8_t*) (tlmBuffer + 1) );

    bestStarIndex->star3Index = *( (uint8_t*) (tlmBuffer + 2) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqBestStarSelectionTimeTlm(uint8_t nodeid, CUBESTAR3_BestStarSelectionTime_t* bestStarSelectionTime)
{
    uint8_t tlmId = 163;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (bestStarSelectionTime == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 4);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    bestStarSelectionTime->latestTime = *( (uint16_t*) (tlmBuffer + 0) );

    bestStarSelectionTime->maxTime = *( (uint16_t*) (tlmBuffer + 2) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqBodyUnitVectorsTlm(uint8_t nodeid, CUBESTAR3_BodyUnitVectors_t* bodyUnitVectors)
{
    uint8_t tlmId = 152;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    int16_t rawVbX;
    int16_t rawVbY;
    int16_t rawVbZ;
    I2C_TransferReturn_TypeDef i2cResult;

    if (bodyUnitVectors == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 7);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    rawVbX = *( (int16_t*) (tlmBuffer + 0) );
    bodyUnitVectors->vbX = rawVbX/10000.0;

    rawVbY = *( (int16_t*) (tlmBuffer + 2) );
    bodyUnitVectors->vbY = rawVbY/10000.0;

    rawVbZ = *( (int16_t*) (tlmBuffer + 4) );
    bodyUnitVectors->vbZ = rawVbZ/10000.0;

    bodyUnitVectors->starNumber = *( (uint8_t*) (tlmBuffer + 6) );

    if ((bodyUnitVectors->vbX < -1) || (bodyUnitVectors->vbX > 1))
        return TlmRangeError;

    if ((bodyUnitVectors->vbY < -1) || (bodyUnitVectors->vbY > 1))
        return TlmRangeError;

    if ((bodyUnitVectors->vbZ < -1) || (bodyUnitVectors->vbZ > 1))
        return TlmRangeError;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqCameraSetupTlm(uint8_t nodeid, CUBESTAR3_CameraSetup_t* cameraSetup)
{
    uint8_t tlmId = 138;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (cameraSetup == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 14);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    cameraSetup->line = *( (uint16_t*) (tlmBuffer + 0) );

    cameraSetup->misc1 = *( (uint16_t*) (tlmBuffer + 2) );

    cameraSetup->misc2 = *( (uint16_t*) (tlmBuffer + 4) );

    cameraSetup->clock = *( (uint16_t*) (tlmBuffer + 6) );

    cameraSetup->chain = *( (uint16_t*) (tlmBuffer + 8) );

    cameraSetup->ctrl = *( (uint16_t*) (tlmBuffer + 10) );

    cameraSetup->clamp = *( (uint16_t*) (tlmBuffer + 12) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqCameraTimingTlm(uint8_t nodeid, CUBESTAR3_CameraTiming_t* cameraTiming)
{
    uint8_t tlmId = 144;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (cameraTiming == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 6);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    cameraTiming->setupTime = *( (uint16_t*) (tlmBuffer + 0) );

    cameraTiming->exposureUpdateTime = *( (uint16_t*) (tlmBuffer + 2) );

    cameraTiming->captureTime = *( (uint16_t*) (tlmBuffer + 4) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqCentroidGridTlm(uint8_t nodeid, uint8_t* gridSize)
{
    uint8_t tlmId = 148;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (gridSize == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 1);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    *gridSize = *( (uint8_t*) (tlmBuffer + 0) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqDetectionRegionTlm(uint8_t nodeid, CUBESTAR3_DetectionRegion_t* detectionRegion)
{
    uint8_t tlmId = 145;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (detectionRegion == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 9);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    detectionRegion->stepSize = *( (uint8_t*) (tlmBuffer + 0) );

    detectionRegion->xstart = *( (uint16_t*) (tlmBuffer + 1) );

    detectionRegion->xend = *( (uint16_t*) (tlmBuffer + 3) );

    detectionRegion->ystart = *( (uint16_t*) (tlmBuffer + 5) );

    detectionRegion->yend = *( (uint16_t*) (tlmBuffer + 7) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqDetectionSummaryTlm(uint8_t nodeid, CUBESTAR3_DetectionSummary_t* detectionSummary)
{
    uint8_t tlmId = 150;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (detectionSummary == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 4);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    detectionSummary->numStarsDetected = *( (uint8_t*) (tlmBuffer + 0) );

    detectionSummary->numInvalidStars = *( (uint8_t*) (tlmBuffer + 1) );

    detectionSummary->amountOfNoise = *( (uint8_t*) (tlmBuffer + 2) );

    detectionSummary->imageDarkValue = *( (uint8_t*) (tlmBuffer + 3) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqDetectionThresholdValuesTlm(uint8_t nodeid, CUBESTAR3_DetectionThresholdValues_t* detectionThresholdValues)
{
    uint8_t tlmId = 146;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (detectionThresholdValues == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 3);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    detectionThresholdValues->darkThreshold = *( (uint8_t*) (tlmBuffer + 0) );

    detectionThresholdValues->detectionThreshold = *( (uint8_t*) (tlmBuffer + 1) );

    detectionThresholdValues->starThreshold = *( (uint8_t*) (tlmBuffer + 2) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqDetectionTimingOneTlm(uint8_t nodeid, CUBESTAR3_DetectionTimingOne_t* detectionTimingOne)
{
    uint8_t tlmId = 153;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (detectionTimingOne == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 8);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    detectionTimingOne->maxStarSearchTime = *( (uint16_t*) (tlmBuffer + 0) );

    detectionTimingOne->maxCentroidFindTime = *( (uint16_t*) (tlmBuffer + 2) );

    detectionTimingOne->maxCorrectionTime = *( (uint16_t*) (tlmBuffer + 4) );

    detectionTimingOne->maxVectorCalTime = *( (uint16_t*) (tlmBuffer + 6) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqDetectionTimingTwoTlm(uint8_t nodeid, CUBESTAR3_DetectionTimingTwo_t* detectionTimingTwo)
{
    uint8_t tlmId = 154;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (detectionTimingTwo == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 4);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    detectionTimingTwo->starDetectionTime = *( (uint16_t*) (tlmBuffer + 0) );

    detectionTimingTwo->maxStarDetectionTime = *( (uint16_t*) (tlmBuffer + 2) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqDistortionCoefTlm(uint8_t nodeid, CUBESTAR3_DistortionCoef_t* distortionCoef)
{
    uint8_t tlmId = 141;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (distortionCoef == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 16);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    distortionCoef->k1 = *((float*)(tlmBuffer + 0));

    distortionCoef->k2 = *((float*)(tlmBuffer + 4));

    distortionCoef->p1 = *((float*)(tlmBuffer + 8));

    distortionCoef->p2 = *((float*)(tlmBuffer + 12));

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqErrorFlagsTlm(uint8_t nodeid, CUBESTAR3_ErrorFlags_t* errorFlags)
{
    uint8_t tlmId = 130;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (errorFlags == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 10);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    errorFlags->overCurrent = (tlmBuffer[0] & 0x01) >> 0;

    errorFlags->underCurrent = (tlmBuffer[0] & 0x02) >> 1;

    errorFlags->uART_ProtocolError = (tlmBuffer[1] & 0x01) >> 0;

    errorFlags->uART_TcmdBufOfError = (tlmBuffer[1] & 0x02) >> 1;

    errorFlags->uART_Tcmd_TooManyParm = (tlmBuffer[1] & 0x04) >> 2;

    errorFlags->uART_Tcmd_TooFewParm = (tlmBuffer[1] & 0x08) >> 3;

    errorFlags->uART_MsgIncomplete = (tlmBuffer[1] & 0x10) >> 4;

    errorFlags->uART_RXTimeout = (tlmBuffer[1] & 0x20) >> 5;

    errorFlags->i2C_WaitForIDReadRequestError = (tlmBuffer[2] & 0x01) >> 0;

    errorFlags->i2C_TcmdBufOFError = (tlmBuffer[2] & 0x02) >> 1;

    errorFlags->i2C_TCMD_TooFewParm = (tlmBuffer[2] & 0x04) >> 2;

    errorFlags->i2C_TCMD_TooManyparm = (tlmBuffer[2] & 0x08) >> 3;

    errorFlags->sPICommsError = (tlmBuffer[3] & 0x01) >> 0;

    errorFlags->statusError = (tlmBuffer[3] & 0x02) >> 1;

    errorFlags->iSSetupError = (tlmBuffer[3] & 0x04) >> 2;

    errorFlags->testPatternConfigError = (tlmBuffer[3] & 0x08) >> 3;

    errorFlags->imageCaptureError = (tlmBuffer[3] & 0x10) >> 4;

    errorFlags->iSDisableError = (tlmBuffer[3] & 0x20) >> 5;

    errorFlags->configChangeError = (tlmBuffer[3] & 0x40) >> 6;

    errorFlags->iSEnableError = (tlmBuffer[3] & 0x80) >> 7;

    errorFlags->focalLengthRangeError = (tlmBuffer[4] & 0x01) >> 0;

    errorFlags->principalPointRangeError = (tlmBuffer[4] & 0x02) >> 1;

    errorFlags->imageBlockSizeError = (tlmBuffer[5] & 0x01) >> 0;

    errorFlags->mainLoopTimeError = (tlmBuffer[5] & 0x02) >> 1;

    errorFlags->tcmdIDError = (tlmBuffer[5] & 0x04) >> 2;

    errorFlags->tlmIDError = (tlmBuffer[5] & 0x08) >> 3;

    errorFlags->triggerAlreadySet = (tlmBuffer[5] & 0x10) >> 4;

    errorFlags->timerAlreadyRunning = (tlmBuffer[5] & 0x20) >> 5;

    errorFlags->timerTimeSetToLong = (tlmBuffer[5] & 0x40) >> 6;

    errorFlags->starPixSetError = (tlmBuffer[6] & 0x01) >> 0;

    errorFlags->maxStarsSetError = (tlmBuffer[6] & 0x02) >> 1;

    errorFlags->maxStarsDetection = (tlmBuffer[6] & 0x04) >> 2;

    errorFlags->maxInvalidStarsDetectionError = (tlmBuffer[6] & 0x08) >> 3;

    errorFlags->centroidingGridSizeSetError = (tlmBuffer[6] & 0x10) >> 4;

    errorFlags->validImageRangeSetError = (tlmBuffer[6] & 0x20) >> 5;

    errorFlags->maxNoiseSetError = (tlmBuffer[6] & 0x40) >> 6;

    errorFlags->maxNoiseDetected = (tlmBuffer[6] & 0x80) >> 7;

    errorFlags->setIDModeError = (tlmBuffer[7] & 0x01) >> 0;

    errorFlags->iDModeError = (tlmBuffer[7] & 0x02) >> 1;

    errorFlags->reducedIDListSizeError = (tlmBuffer[7] & 0x04) >> 2;

    errorFlags->lessThanThreeStarsInFoV = (tlmBuffer[7] & 0x08) >> 3;

    errorFlags->lessThanThreeStarsDetected = (tlmBuffer[7] & 0x10) >> 4;

    errorFlags->lessThanThreeStarsID = (tlmBuffer[7] & 0x20) >> 5;

    errorFlags->iDError = (tlmBuffer[7] & 0x40) >> 6;

    errorFlags->iDSearchError = (tlmBuffer[7] & 0x80) >> 7;

    errorFlags->declinationSetError = (tlmBuffer[8] & 0x01) >> 0;

    errorFlags->rightAscensionSetError = (tlmBuffer[8] & 0x02) >> 1;

    errorFlags->questindexError = (tlmBuffer[8] & 0x04) >> 2;

    errorFlags->rateExceeded = (tlmBuffer[8] & 0x08) >> 3;

    errorFlags->flashInvalidAreaError = (tlmBuffer[9] & 0x01) >> 0;

    errorFlags->flashLockedError = (tlmBuffer[9] & 0x02) >> 1;

    errorFlags->flashTimeoutError = (tlmBuffer[9] & 0x04) >> 2;

    errorFlags->flashUnalignedError = (tlmBuffer[9] & 0x08) >> 3;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqExposureTlm(uint8_t nodeid, uint16_t* exposure)
{
    uint8_t tlmId = 136;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (exposure == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 2);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    *exposure = *( (uint16_t*) (tlmBuffer + 0) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqExtendedIdentificationTlm(uint8_t nodeid, CUBESTAR3_ExtendedIdentification_t* extendedIdentification)
{
    uint8_t tlmId = 129;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    int16_t rawTemperature;
    I2C_TransferReturn_TypeDef i2cResult;
    uint8_t enumVal;

    if (extendedIdentification == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 11);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    extendedIdentification->serialNumber = *( (uint16_t*) (tlmBuffer + 0) );

    rawTemperature = *( (int16_t*) (tlmBuffer + 2) );
    extendedIdentification->temperature = rawTemperature/100.0;

    enumVal = tlmBuffer[4];
    extendedIdentification->resetCause = (CUBESTAR3_ResetCause_t) enumVal;

    extendedIdentification->wDGResetCount = *( (uint16_t*) (tlmBuffer + 5) );

    extendedIdentification->tcmdCount = *( (uint16_t*) (tlmBuffer + 7) );

    extendedIdentification->tlmCount = *( (uint16_t*) (tlmBuffer + 9) );

    if ((extendedIdentification->resetCause < 0) || (extendedIdentification->resetCause > 10))
        return TlmRangeError;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqFocalLengthDetailsTlm(uint8_t nodeid, CUBESTAR3_FocalLengthDetails_t* focalLengthDetails)
{
    uint8_t tlmId = 139;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (focalLengthDetails == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 12);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    focalLengthDetails->focalLength = *((float*)(tlmBuffer + 0));

    focalLengthDetails->fx = *((float*)(tlmBuffer + 4));

    focalLengthDetails->fy = *((float*)(tlmBuffer + 8));

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqIDDistanceMarginTlm(uint8_t nodeid, double* iDmargin)
{
    uint8_t tlmId = 156;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    uint8_t rawIDmargin;
    I2C_TransferReturn_TypeDef i2cResult;

    if (iDmargin == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 1);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    rawIDmargin = *( (uint8_t*) (tlmBuffer + 0) );
    *iDmargin = rawIDmargin/10000.0;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqIdentificationTlm(uint8_t nodeid, CUBESTAR3_Identification_t* identification)
{
    uint8_t tlmId = 128;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (identification == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 8);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    identification->nodeType = *( (uint8_t*) (tlmBuffer + 0) );

    identification->interfaceVersion = *( (uint8_t*) (tlmBuffer + 1) );

    identification->firmwareVersionMajor = *( (uint8_t*) (tlmBuffer + 2) );

    identification->firmwareVersionMinor = *( (uint8_t*) (tlmBuffer + 3) );

    identification->runtimeMilliseconds = *( (uint16_t*) (tlmBuffer + 4) );

    identification->runtimeSeconds = *( (uint16_t*) (tlmBuffer + 6) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqIDModeTlm(uint8_t nodeid, CUBESTAR3_IDModeVal_t* iDMode)
{
    uint8_t tlmId = 155;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;
    uint8_t enumVal;

    if (iDMode == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 1);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    enumVal = tlmBuffer[0];
    *iDMode = (CUBESTAR3_IDModeVal_t) enumVal;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqIDStarsDetailsTlm(uint8_t nodeid, CUBESTAR3_IDStarsDetails_t* iDStarsDetails)
{
    uint8_t tlmId = 158;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (iDStarsDetails == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 5);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    iDStarsDetails->starNumber = *( (uint8_t*) (tlmBuffer + 0) );

    iDStarsDetails->identity = *( (uint16_t*) (tlmBuffer + 1) );

    iDStarsDetails->validationVotes = *( (uint8_t*) (tlmBuffer + 3) );

    iDStarsDetails->confidence = *( (uint8_t*) (tlmBuffer + 4) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqIDTimingOneTlm(uint8_t nodeid, CUBESTAR3_IDTimingOne_t* iDTimingOne)
{
    uint8_t tlmId = 160;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (iDTimingOne == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 8);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    iDTimingOne->maxModeSelectionTime = *( (uint16_t*) (tlmBuffer + 0) );

    iDTimingOne->maxDistanceCalTime = *( (uint16_t*) (tlmBuffer + 2) );

    iDTimingOne->maxVoteRoundOneTime = *( (uint16_t*) (tlmBuffer + 4) );

    iDTimingOne->maxFindIDTime = *( (uint16_t*) (tlmBuffer + 6) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqIDTimingThreeTlm(uint8_t nodeid, CUBESTAR3_IDTimingThree_t* iDTimingThree)
{
    uint8_t tlmId = 162;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (iDTimingThree == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 4);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    iDTimingThree->starIdentificationTime = *( (uint16_t*) (tlmBuffer + 0) );

    iDTimingThree->maxStarIdentificationTime = *( (uint16_t*) (tlmBuffer + 2) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqIDTimingTwoTlm(uint8_t nodeid, CUBESTAR3_IDTimingTwo_t* iDTimingTwo)
{
    uint8_t tlmId = 161;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (iDTimingTwo == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 6);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    iDTimingTwo->maxVoteRoundTwoTime = *( (uint16_t*) (tlmBuffer + 0) );

    iDTimingTwo->maxSelectID = *( (uint16_t*) (tlmBuffer + 2) );

    iDTimingTwo->maxAlgoCompletionTime = *( (uint16_t*) (tlmBuffer + 4) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqImageBlockTlm(uint8_t nodeid, uint8_t* imageBlock)
{
    uint8_t tlmId = 143;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (imageBlock == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 128);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    memcpy(imageBlock, tlmBuffer + 0, 128);

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqImageSetupTlm(uint8_t nodeid, CUBESTAR3_ImageSetup_t* imageSetup)
{
    uint8_t tlmId = 137;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (imageSetup == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 6);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    imageSetup->firstLine = *( (uint16_t*) (tlmBuffer + 0) );

    imageSetup->width = *( (uint16_t*) (tlmBuffer + 2) );

    imageSetup->height = *( (uint16_t*) (tlmBuffer + 4) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqInertialUnitVectorsTlm(uint8_t nodeid, CUBESTAR3_InertialUnitVectors_t* inertialUnitVectors)
{
    uint8_t tlmId = 159;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    int16_t rawViX;
    int16_t rawViY;
    int16_t rawViZ;
    I2C_TransferReturn_TypeDef i2cResult;

    if (inertialUnitVectors == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 10);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    rawViX = *( (int16_t*) (tlmBuffer + 0) );
    inertialUnitVectors->viX = rawViX/10000.0;

    rawViY = *( (int16_t*) (tlmBuffer + 2) );
    inertialUnitVectors->viY = rawViY/10000.0;

    rawViZ = *( (int16_t*) (tlmBuffer + 4) );
    inertialUnitVectors->viZ = rawViZ/10000.0;

    inertialUnitVectors->starNumber = *( (uint8_t*) (tlmBuffer + 6) );

    inertialUnitVectors->identity = *( (uint16_t*) (tlmBuffer + 7) );

    inertialUnitVectors->confidence = *( (uint8_t*) (tlmBuffer + 9) );

    if ((inertialUnitVectors->viX < -1) || (inertialUnitVectors->viX > 1))
        return TlmRangeError;

    if ((inertialUnitVectors->viY < -1) || (inertialUnitVectors->viY > 1))
        return TlmRangeError;

    if ((inertialUnitVectors->viZ < -1) || (inertialUnitVectors->viZ > 1))
        return TlmRangeError;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqIS_RegisterTlm(uint8_t nodeid, CUBESTAR3_IS_Register_t* iS_Register)
{
    uint8_t tlmId = 142;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (iS_Register == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 2);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    iS_Register->dataH = *( (uint8_t*) (tlmBuffer + 0) );

    iS_Register->dataL = *( (uint8_t*) (tlmBuffer + 1) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqLogStatusTlm(uint8_t nodeid, CUBESTAR3_LogStatus_t* logStatus)
{
    uint8_t tlmId = 174;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    int16_t rawTemp;
    I2C_TransferReturn_TypeDef i2cResult;
    uint8_t enumVal;

    if (logStatus == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 26);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    rawTemp = *( (int16_t*) (tlmBuffer + 0) );
    logStatus->temp = rawTemp/100.0;

    logStatus->runtime = *( (uint32_t*) (tlmBuffer + 2) );

    logStatus->wDGcounter = *( (uint16_t*) (tlmBuffer + 6) );

    enumVal = tlmBuffer[8];
    logStatus->status = (CUBESTAR3_TaskStatusVal_t) enumVal;

    logStatus->sW = *( (uint8_t*) (tlmBuffer + 9) );

    logStatus->current = *( (uint16_t*) (tlmBuffer + 10) );

    logStatus->maxCurrent = *( (uint16_t*) (tlmBuffer + 12) );

    logStatus->minCurrent = *( (uint16_t*) (tlmBuffer + 14) );

    logStatus->overCurrent = (tlmBuffer[16] & 0x01) >> 0;

    logStatus->underCurrent = (tlmBuffer[16] & 0x02) >> 1;

    logStatus->uART_ProtocolError = (tlmBuffer[17] & 0x01) >> 0;

    logStatus->uART_TcmdBufOfError = (tlmBuffer[17] & 0x02) >> 1;

    logStatus->uART_Tcmd_TooManyParm = (tlmBuffer[17] & 0x04) >> 2;

    logStatus->uART_Tcmd_TooFewParm = (tlmBuffer[17] & 0x08) >> 3;

    logStatus->uART_MsgIncomplete = (tlmBuffer[17] & 0x10) >> 4;

    logStatus->uART_RXTimeout = (tlmBuffer[17] & 0x20) >> 5;

    logStatus->i2C_WaitForIDReadRequestError = (tlmBuffer[18] & 0x01) >> 0;

    logStatus->i2C_TcmdBufOFError = (tlmBuffer[18] & 0x02) >> 1;

    logStatus->i2C_TCMD_TooFewParm = (tlmBuffer[18] & 0x04) >> 2;

    logStatus->i2C_TCMD_TooManyparm = (tlmBuffer[18] & 0x08) >> 3;

    logStatus->sPICommsError = (tlmBuffer[19] & 0x01) >> 0;

    logStatus->statusError = (tlmBuffer[19] & 0x02) >> 1;

    logStatus->iSsetupError = (tlmBuffer[19] & 0x04) >> 2;

    logStatus->testpatternConfigError = (tlmBuffer[19] & 0x08) >> 3;

    logStatus->imageCaptureError = (tlmBuffer[19] & 0x10) >> 4;

    logStatus->iSDisableError = (tlmBuffer[19] & 0x20) >> 5;

    logStatus->configChangeError = (tlmBuffer[19] & 0x40) >> 6;

    logStatus->iSEnableError = (tlmBuffer[19] & 0x80) >> 7;

    logStatus->focalLengthRangeError = (tlmBuffer[20] & 0x01) >> 0;

    logStatus->boresightRangeError = (tlmBuffer[20] & 0x02) >> 1;

    logStatus->imageBlockSizeError = (tlmBuffer[21] & 0x01) >> 0;

    logStatus->mainLoopTimeError = (tlmBuffer[21] & 0x02) >> 1;

    logStatus->tcmdIDError = (tlmBuffer[21] & 0x04) >> 2;

    logStatus->tlmIDError = (tlmBuffer[21] & 0x08) >> 3;

    logStatus->triggerAlreadySet = (tlmBuffer[21] & 0x10) >> 4;

    logStatus->timerAlreadyRunning = (tlmBuffer[21] & 0x20) >> 5;

    logStatus->timerTimeSetToLong = (tlmBuffer[21] & 0x40) >> 6;

    logStatus->pixSetError = (tlmBuffer[22] & 0x01) >> 0;

    logStatus->maxStarsSetError = (tlmBuffer[22] & 0x02) >> 1;

    logStatus->maxStarsDetection = (tlmBuffer[22] & 0x04) >> 2;

    logStatus->maxInvalidStarsDetectionError = (tlmBuffer[22] & 0x08) >> 3;

    logStatus->centroidingGridSizeSetError = (tlmBuffer[22] & 0x10) >> 4;

    logStatus->validImageRangeSetError = (tlmBuffer[22] & 0x20) >> 5;

    logStatus->maxNoiseSetError = (tlmBuffer[22] & 0x40) >> 6;

    logStatus->maxNoiseDetected = (tlmBuffer[22] & 0x80) >> 7;

    logStatus->setIDModeError = (tlmBuffer[23] & 0x01) >> 0;

    logStatus->iDModeError = (tlmBuffer[23] & 0x02) >> 1;

    logStatus->reducedIDListSizeError = (tlmBuffer[23] & 0x04) >> 2;

    logStatus->lessThanThreeStarsInFoV = (tlmBuffer[23] & 0x08) >> 3;

    logStatus->lessThanThreeStarsDetected = (tlmBuffer[23] & 0x10) >> 4;

    logStatus->lessThanThreeStarsID = (tlmBuffer[23] & 0x20) >> 5;

    logStatus->iDError = (tlmBuffer[23] & 0x40) >> 6;

    logStatus->iDSearchError = (tlmBuffer[23] & 0x80) >> 7;

    logStatus->declinationSetError = (tlmBuffer[24] & 0x01) >> 0;

    logStatus->rightAscensionSetError = (tlmBuffer[24] & 0x02) >> 1;

    logStatus->questindexError = (tlmBuffer[24] & 0x04) >> 2;

    logStatus->rateExceeded = (tlmBuffer[24] & 0x08) >> 3;

    logStatus->flashInvalidAreaError = (tlmBuffer[25] & 0x01) >> 0;

    logStatus->flashLockedError = (tlmBuffer[25] & 0x02) >> 1;

    logStatus->flashTimeoutError = (tlmBuffer[25] & 0x04) >> 2;

    logStatus->flashUnalignedError = (tlmBuffer[25] & 0x08) >> 3;

    if ((logStatus->status < 0) || (logStatus->status > 39))
        return TlmRangeError;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqMaxStarsTlm(uint8_t nodeid, CUBESTAR3_MaxStars_t* maxStars)
{
    uint8_t tlmId = 149;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (maxStars == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 3);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    maxStars->maxStars = *( (uint8_t*) (tlmBuffer + 0) );

    maxStars->maxInvalidStars = *( (uint8_t*) (tlmBuffer + 1) );

    maxStars->maxNoise = *( (uint8_t*) (tlmBuffer + 2) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqNumIdStarsTlm(uint8_t nodeid, uint8_t* numIdStars)
{
    uint8_t tlmId = 157;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (numIdStars == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 1);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    *numIdStars = *( (uint8_t*) (tlmBuffer + 0) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqPerformanceParametersTlm(uint8_t nodeid, CUBESTAR3_PerformanceParameters_t* performanceParameters)
{
    uint8_t tlmId = 167;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;
    uint8_t enumVal;

    if (performanceParameters == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 7);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    performanceParameters->numStarsDetected = *( (uint8_t*) (tlmBuffer + 0) );

    performanceParameters->starImageNoise = *( (uint8_t*) (tlmBuffer + 1) );

    performanceParameters->invalidStars = *( (uint8_t*) (tlmBuffer + 2) );

    performanceParameters->numberOfStarsID = *( (uint8_t*) (tlmBuffer + 3) );

    enumVal = tlmBuffer[4];
    performanceParameters->idmode = (CUBESTAR3_IDModeVal_t) enumVal;

    performanceParameters->imageDarkValue = *( (uint8_t*) (tlmBuffer + 5) );

    performanceParameters->imageCaptureSuccess = (tlmBuffer[6] & 0x01) >> 0;

    performanceParameters->detectionSuccess = (tlmBuffer[6] & 0x02) >> 1;

    performanceParameters->identificationSuccess = (tlmBuffer[6] & 0x04) >> 2;

    performanceParameters->attitudeSuccess = (tlmBuffer[6] & 0x08) >> 3;

    performanceParameters->processingTimeError = (tlmBuffer[6] & 0x10) >> 4;

    performanceParameters->maxStarsDetected = (tlmBuffer[6] & 0x20) >> 5;

    performanceParameters->lessThanThreeStarsInFoV = (tlmBuffer[6] & 0x40) >> 6;

    performanceParameters->commsError = (tlmBuffer[6] & 0x80) >> 7;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqPowerStatusTlm(uint8_t nodeid, CUBESTAR3_PowerStatus_t* powerStatus)
{
    uint8_t tlmId = 135;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (powerStatus == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 7);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    powerStatus->status = *( (uint8_t*) (tlmBuffer + 0) );

    powerStatus->current = *( (uint16_t*) (tlmBuffer + 1) );

    powerStatus->maxCurrent = *( (uint16_t*) (tlmBuffer + 3) );

    powerStatus->minCurrent = *( (uint16_t*) (tlmBuffer + 5) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqPrincipalPointTlm(uint8_t nodeid, CUBESTAR3_PrincipalPoint_t* principalPoint)
{
    uint8_t tlmId = 140;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (principalPoint == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 8);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    principalPoint->cx = *((float*)(tlmBuffer + 0));

    principalPoint->cy = *((float*)(tlmBuffer + 4));

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqQuaternionTlm(uint8_t nodeid, CUBESTAR3_Quaternion_t* quaternion)
{
    uint8_t tlmId = 164;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    int16_t rawQbar0;
    int16_t rawQbar1;
    int16_t rawQbar2;
    int16_t rawQbar3;
    I2C_TransferReturn_TypeDef i2cResult;

    if (quaternion == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 8);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    rawQbar0 = *( (int16_t*) (tlmBuffer + 0) );
    quaternion->qbar0 = rawQbar0/10000.0;

    rawQbar1 = *( (int16_t*) (tlmBuffer + 2) );
    quaternion->qbar1 = rawQbar1/10000.0;

    rawQbar2 = *( (int16_t*) (tlmBuffer + 4) );
    quaternion->qbar2 = rawQbar2/10000.0;

    rawQbar3 = *( (int16_t*) (tlmBuffer + 6) );
    quaternion->qbar3 = rawQbar3/10000.0;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqResultsTlm(uint8_t nodeid, CUBESTAR3_Results_t* results)
{
    uint8_t tlmId = 175;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (results == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 6);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    results->darkValue = *( (uint8_t*) (tlmBuffer + 0) );

    results->detected = *( (uint8_t*) (tlmBuffer + 1) );

    results->invalid = *( (uint8_t*) (tlmBuffer + 2) );

    results->noise = *( (uint8_t*) (tlmBuffer + 3) );

    results->iDMode = *( (uint8_t*) (tlmBuffer + 4) );

    results->iD = *( (uint8_t*) (tlmBuffer + 5) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqSphereicalCoordinatesTlm(uint8_t nodeid, CUBESTAR3_SphereicalCoordinates_t* sphereicalCoordinates)
{
    uint8_t tlmId = 165;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (sphereicalCoordinates == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 8);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    sphereicalCoordinates->declination = *((float*)(tlmBuffer + 0));

    sphereicalCoordinates->rightAscension = *((float*)(tlmBuffer + 4));

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqSRAMTestResultsTlm(uint8_t nodeid, uint8_t* sramTestResults)
{
    uint8_t tlmId = 134;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (sramTestResults == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 1);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    *sramTestResults = *( (uint8_t*) (tlmBuffer + 0) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqStar1VectorsTlm(uint8_t nodeid, CUBESTAR3_Star1Vectors_t* star1Vectors)
{
    uint8_t tlmId = 170;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    int16_t rawS1VBX;
    int16_t rawS1VBY;
    int16_t rawS1VBZ;
    int16_t rawS1VIX;
    int16_t rawS1VIY;
    int16_t rawS1VIZ;
    I2C_TransferReturn_TypeDef i2cResult;

    if (star1Vectors == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 21);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    star1Vectors->s1CentX = *( (uint16_t*) (tlmBuffer + 0) );

    star1Vectors->s1CentY = *( (uint16_t*) (tlmBuffer + 2) );

    star1Vectors->s1Mag = *( (uint16_t*) (tlmBuffer + 4) );

    rawS1VBX = *( (int16_t*) (tlmBuffer + 6) );
    star1Vectors->s1VBX = rawS1VBX/10000.0;

    rawS1VBY = *( (int16_t*) (tlmBuffer + 8) );
    star1Vectors->s1VBY = rawS1VBY/10000.0;

    rawS1VBZ = *( (int16_t*) (tlmBuffer + 10) );
    star1Vectors->s1VBZ = rawS1VBZ/10000.0;

    rawS1VIX = *( (int16_t*) (tlmBuffer + 12) );
    star1Vectors->s1VIX = rawS1VIX/10000.0;

    rawS1VIY = *( (int16_t*) (tlmBuffer + 14) );
    star1Vectors->s1VIY = rawS1VIY/10000.0;

    rawS1VIZ = *( (int16_t*) (tlmBuffer + 16) );
    star1Vectors->s1VIZ = rawS1VIZ/10000.0;

    star1Vectors->s1Conf = *( (uint8_t*) (tlmBuffer + 18) );

    star1Vectors->s1CatNum = *( (uint16_t*) (tlmBuffer + 19) );

    if ((star1Vectors->s1VBX < -1) || (star1Vectors->s1VBX > 1))
        return TlmRangeError;

    if ((star1Vectors->s1VBY < -1) || (star1Vectors->s1VBY > 1))
        return TlmRangeError;

    if ((star1Vectors->s1VBZ < -1) || (star1Vectors->s1VBZ > 1))
        return TlmRangeError;

    if ((star1Vectors->s1VIX < -1) || (star1Vectors->s1VIX > 1))
        return TlmRangeError;

    if ((star1Vectors->s1VIY < -1) || (star1Vectors->s1VIY > 1))
        return TlmRangeError;

    if ((star1Vectors->s1VIZ < -1) || (star1Vectors->s1VIZ > 1))
        return TlmRangeError;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqStar2VectorsTlm(uint8_t nodeid, CUBESTAR3_Star2Vectors_t* star2Vectors)
{
    uint8_t tlmId = 171;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    int16_t rawS2VBX;
    int16_t rawS2VBY;
    int16_t rawS2VBZ;
    int16_t rawS2VIX;
    int16_t rawS2VIY;
    int16_t rawS2VIZ;
    I2C_TransferReturn_TypeDef i2cResult;

    if (star2Vectors == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 21);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    star2Vectors->s2CentX = *( (uint16_t*) (tlmBuffer + 0) );

    star2Vectors->s2CentY = *( (uint16_t*) (tlmBuffer + 2) );

    star2Vectors->s2Mag = *( (uint16_t*) (tlmBuffer + 4) );

    rawS2VBX = *( (int16_t*) (tlmBuffer + 6) );
    star2Vectors->s2VBX = rawS2VBX/10000.0;

    rawS2VBY = *( (int16_t*) (tlmBuffer + 8) );
    star2Vectors->s2VBY = rawS2VBY/10000.0;

    rawS2VBZ = *( (int16_t*) (tlmBuffer + 10) );
    star2Vectors->s2VBZ = rawS2VBZ/10000.0;

    rawS2VIX = *( (int16_t*) (tlmBuffer + 12) );
    star2Vectors->s2VIX = rawS2VIX/10000.0;

    rawS2VIY = *( (int16_t*) (tlmBuffer + 14) );
    star2Vectors->s2VIY = rawS2VIY/10000.0;

    rawS2VIZ = *( (int16_t*) (tlmBuffer + 16) );
    star2Vectors->s2VIZ = rawS2VIZ/10000.0;

    star2Vectors->s2Conf = *( (uint8_t*) (tlmBuffer + 18) );

    star2Vectors->s2CatNum = *( (uint16_t*) (tlmBuffer + 19) );

    if ((star2Vectors->s2VBX < -1) || (star2Vectors->s2VBX > 1))
        return TlmRangeError;

    if ((star2Vectors->s2VBY < -1) || (star2Vectors->s2VBY > 1))
        return TlmRangeError;

    if ((star2Vectors->s2VBZ < -1) || (star2Vectors->s2VBZ > 1))
        return TlmRangeError;

    if ((star2Vectors->s2VIX < -1) || (star2Vectors->s2VIX > 1))
        return TlmRangeError;

    if ((star2Vectors->s2VIY < -1) || (star2Vectors->s2VIY > 1))
        return TlmRangeError;

    if ((star2Vectors->s2VIZ < -1) || (star2Vectors->s2VIZ > 1))
        return TlmRangeError;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqStar3VectorsTlm(uint8_t nodeid, CUBESTAR3_Star3Vectors_t* star3Vectors)
{
    uint8_t tlmId = 172;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    int16_t rawS3VBX;
    int16_t rawS3VBY;
    int16_t rawS3VBZ;
    int16_t rawS3VIX;
    int16_t rawS3VIY;
    int16_t rawS3VIZ;
    I2C_TransferReturn_TypeDef i2cResult;

    if (star3Vectors == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 21);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    star3Vectors->s3CentX = *( (uint16_t*) (tlmBuffer + 0) );

    star3Vectors->s3CentY = *( (uint16_t*) (tlmBuffer + 2) );

    star3Vectors->s3Mag = *( (uint16_t*) (tlmBuffer + 4) );

    rawS3VBX = *( (int16_t*) (tlmBuffer + 6) );
    star3Vectors->s3VBX = rawS3VBX/10000.0;

    rawS3VBY = *( (int16_t*) (tlmBuffer + 8) );
    star3Vectors->s3VBY = rawS3VBY/10000.0;

    rawS3VBZ = *( (int16_t*) (tlmBuffer + 10) );
    star3Vectors->s3VBZ = rawS3VBZ/10000.0;

    rawS3VIX = *( (int16_t*) (tlmBuffer + 12) );
    star3Vectors->s3VIX = rawS3VIX/10000.0;

    rawS3VIY = *( (int16_t*) (tlmBuffer + 14) );
    star3Vectors->s3VIY = rawS3VIY/10000.0;

    rawS3VIZ = *( (int16_t*) (tlmBuffer + 16) );
    star3Vectors->s3VIZ = rawS3VIZ/10000.0;

    star3Vectors->s3Conf = *( (uint8_t*) (tlmBuffer + 18) );

    star3Vectors->s3CatNum = *( (uint16_t*) (tlmBuffer + 19) );

    if ((star3Vectors->s3VBX < -1) || (star3Vectors->s3VBX > 1))
        return TlmRangeError;

    if ((star3Vectors->s3VBY < -1) || (star3Vectors->s3VBY > 1))
        return TlmRangeError;

    if ((star3Vectors->s3VBZ < -1) || (star3Vectors->s3VBZ > 1))
        return TlmRangeError;

    if ((star3Vectors->s3VIX < -1) || (star3Vectors->s3VIX > 1))
        return TlmRangeError;

    if ((star3Vectors->s3VIY < -1) || (star3Vectors->s3VIY > 1))
        return TlmRangeError;

    if ((star3Vectors->s3VIZ < -1) || (star3Vectors->s3VIZ > 1))
        return TlmRangeError;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqStarDetailsTlm(uint8_t nodeid, CUBESTAR3_StarDetails_t* starDetails)
{
    uint8_t tlmId = 176;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (starDetails == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 22);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    starDetails->starNumber = *( (uint8_t*) (tlmBuffer + 0) );

    starDetails->cCx = *((float*)(tlmBuffer + 1));

    starDetails->cCy = *((float*)(tlmBuffer + 5));

    starDetails->vbx = *( (int16_t*) (tlmBuffer + 9) );

    starDetails->vby = *( (int16_t*) (tlmBuffer + 11) );

    starDetails->vbz = *( (int16_t*) (tlmBuffer + 13) );

    starDetails->iD = *( (uint16_t*) (tlmBuffer + 15) );

    starDetails->validationVote = *( (uint8_t*) (tlmBuffer + 17) );

    starDetails->confidance = *((float*)(tlmBuffer + 18));

    if ((starDetails->vbx < -1) || (starDetails->vbx > 1))
        return TlmRangeError;

    if ((starDetails->vby < -1) || (starDetails->vby > 1))
        return TlmRangeError;

    if ((starDetails->vbz < -1) || (starDetails->vbz > 1))
        return TlmRangeError;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqStarPixelsTlm(uint8_t nodeid, CUBESTAR3_StarPixels_t* starPixels)
{
    uint8_t tlmId = 147;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (starPixels == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 2);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    starPixels->minPixels = *( (uint8_t*) (tlmBuffer + 0) );

    starPixels->maxPixels = *( (uint8_t*) (tlmBuffer + 1) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqStarPositionsTlm(uint8_t nodeid, CUBESTAR3_StarPositions_t* starPositions)
{
    uint8_t tlmId = 151;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (starPositions == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 20);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    starPositions->x_Coordinate = *((float*)(tlmBuffer + 0));

    starPositions->y_Coordinate = *((float*)(tlmBuffer + 4));

    starPositions->x_CorrectedCoordinate = *((float*)(tlmBuffer + 8));

    starPositions->y_CorrectedCoordinate = *((float*)(tlmBuffer + 12));

    starPositions->starNumber = *( (uint8_t*) (tlmBuffer + 16) );

    starPositions->size = *( (uint8_t*) (tlmBuffer + 17) );

    starPositions->intensity = *( (uint16_t*) (tlmBuffer + 18) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqStartAndLoopTimeTlm(uint8_t nodeid, CUBESTAR3_StartAndLoopTime_t* startAndLoopTime)
{
    uint8_t tlmId = 133;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (startAndLoopTime == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 6);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    startAndLoopTime->startupTime = *( (uint16_t*) (tlmBuffer + 0) );

    startAndLoopTime->loopTime = *( (uint16_t*) (tlmBuffer + 2) );

    startAndLoopTime->maxLoopTime = *( (uint16_t*) (tlmBuffer + 4) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqTaskStatusTlm(uint8_t nodeid, CUBESTAR3_TaskStatusVal_t* taskStatus)
{
    uint8_t tlmId = 132;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;
    uint8_t enumVal;

    if (taskStatus == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 1);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    enumVal = tlmBuffer[0];
    *taskStatus = (CUBESTAR3_TaskStatusVal_t) enumVal;

    if ((*taskStatus < 0) || (*taskStatus > 39))
        return TlmRangeError;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqTcmdProcessedTlm(uint8_t nodeid, uint8_t* processed)
{
    uint8_t tlmId = 131;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (processed == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 1);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    *processed = *( (uint8_t*) (tlmBuffer + 0) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqTimerTimeoutTlm(uint8_t nodeid, uint8_t* timeout)
{
    uint8_t tlmId = 173;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (timeout == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 1);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    *timeout = *( (uint8_t*) (tlmBuffer + 0) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_ReqTimingSummaryTlm(uint8_t nodeid, CUBESTAR3_TimingSummary_t* timingSummary)
{
    uint8_t tlmId = 168;
    uint8_t* tlmBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if (timingSummary == 0)
        return PointerIsNull;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE_READ, &tlmId, 1, tlmBuffer, 6);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    BSP_TIME_Delay(2);

    timingSummary->imageCaptureTime = *( (uint16_t*) (tlmBuffer + 0) );

    timingSummary->detectionTime = *( (uint16_t*) (tlmBuffer + 2) );

    timingSummary->identificationTime = *( (uint16_t*) (tlmBuffer + 4) );

    return CubeLibOk;
}


CUBELIB_Result_t CUBESTAR3_SendCaptureAndProcessCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 36;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendCaptureImageCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 16;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendCaptureTestPaternCmd(uint8_t nodeid, CUBESTAR3_TestPatternType_t testPaternType)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if ((testPaternType < 0) || (testPaternType > 2))
        return TcInvalidParam;

    if (((testPaternType < 0) || (testPaternType > 2)))
        return TcInvalidParam;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 15;

    tcBuffer[1] = 
        (testPaternType << 0);

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 2, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendClearConfigCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 33;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendClearErrorFlagsCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 6;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendClearWDGResetCounterCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 5;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendDetectStarsCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 24;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendEstimateAttitudeCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 30;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendIDStarsCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 28;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendImageBlockSetCmd(uint8_t nodeid, uint16_t blockNumber, CUBESTAR3_BlockSize_t blockSize)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if ((blockSize < 0) || (blockSize > 3))
        return TcInvalidParam;

    if (((blockSize < 0) || (blockSize > 3)))
        return TcInvalidParam;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 18;

    tcBuffer[3] = 
        (blockSize << 0);
    *( (uint16_t*)(tcBuffer + 1) ) = blockNumber;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 4, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendMCUResetCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 3;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendProcessImageCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 37;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendReadConfigCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 31;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendReadFrom_IS_RegisterCmd(uint8_t nodeid, uint8_t reg)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 14;

    *( (uint8_t*)(tcBuffer + 1) ) = reg;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 2, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendResetCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 2;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendSaveConfigCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 32;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendSelectBestStarsCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 29;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendsetDetectionRegionCmd(uint8_t nodeid, uint8_t stepSize, uint16_t xstart, uint16_t xend, uint16_t ystart, uint16_t yend)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if ((stepSize < 0) || (stepSize > 10))
        return TcInvalidParam;

    if ((xstart < 0) || (xstart > 343))
        return TcInvalidParam;

    if ((xend < 936) || (xend > 1279))
        return TcInvalidParam;

    if ((ystart < 7) || (ystart > 96))
        return TcInvalidParam;

    if ((yend < 943) || (yend > 1030))
        return TcInvalidParam;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 20;

    *( (uint8_t*)(tcBuffer + 1) ) = stepSize;
    *( (uint16_t*)(tcBuffer + 2) ) = xstart;
    *( (uint16_t*)(tcBuffer + 4) ) = xend;
    *( (uint16_t*)(tcBuffer + 6) ) = ystart;
    *( (uint16_t*)(tcBuffer + 8) ) = yend;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 10, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendsetDetectionThresholdsCmd(uint8_t nodeid, uint8_t detectionThreshold, uint8_t starThreshold)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 21;

    *( (uint8_t*)(tcBuffer + 1) ) = detectionThreshold;
    *( (uint8_t*)(tcBuffer + 2) ) = starThreshold;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 3, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendsetDetectionVariablesCmd(uint8_t nodeid, uint8_t gridSize, uint8_t maxStars, uint8_t maxInvalidStars, uint8_t maxNoise)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if ((gridSize < 0) || (gridSize > 15))
        return TcInvalidParam;

    if ((maxStars < 0) || (maxStars > 99))
        return TcInvalidParam;

    if ((maxInvalidStars < 0) || (maxInvalidStars > 15))
        return TcInvalidParam;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 23;

    *( (uint8_t*)(tcBuffer + 1) ) = gridSize;
    *( (uint8_t*)(tcBuffer + 2) ) = maxStars;
    *( (uint8_t*)(tcBuffer + 3) ) = maxInvalidStars;
    *( (uint8_t*)(tcBuffer + 4) ) = maxNoise;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 5, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendsetExposureCmd(uint8_t nodeid, uint16_t exposure)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 7;

    *( (uint16_t*)(tcBuffer + 1) ) = exposure;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 3, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendsetFocalLengthCmd(uint8_t nodeid, float focalLength)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if ((focalLength < 5) || (focalLength > 7))
        return TcInvalidParam;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 8;

    *( (float*)(tcBuffer + 1) ) = focalLength;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 5, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendsetFocalLengthComponentsCmd(uint8_t nodeid, float fx, float fy)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 9;

    *( (float*)(tcBuffer + 1) ) = fx;
    *( (float*)(tcBuffer + 5) ) = fy;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 9, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendsetIDDistanceMarginCmd(uint8_t nodeid, double iDMargin)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 27;

    *( (uint8_t*)(tcBuffer + 1) ) = (uint8_t) round(iDMargin*10000.0);

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 2, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendsetIDModeCmd(uint8_t nodeid, CUBESTAR3_Mode_t idMode)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if ((idMode < 0) || (idMode > 1))
        return TcInvalidParam;

    if (((idMode < 0) || (idMode > 1)))
        return TcInvalidParam;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 25;

    tcBuffer[1] = 
        (idMode << 0);

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 2, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendsetIDModeTrackingCmd(uint8_t nodeid, float rightAscension, float declination)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 26;

    *( (float*)(tcBuffer + 1) ) = rightAscension;
    *( (float*)(tcBuffer + 5) ) = declination;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 9, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendsetPrincipalPointCmd(uint8_t nodeid, float cx, float cy)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if ((cx < 0) || (cx > 1280))
        return TcInvalidParam;

    if ((cy < 7) || (cy > 1030))
        return TcInvalidParam;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 10;

    *( (float*)(tcBuffer + 1) ) = cx;
    *( (float*)(tcBuffer + 5) ) = cy;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 9, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendsetRadialDistortionGainsCmd(uint8_t nodeid, float k1, float k2)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 11;

    *( (float*)(tcBuffer + 1) ) = k1;
    *( (float*)(tcBuffer + 5) ) = k2;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 9, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendsetStarPixelsCmd(uint8_t nodeid, uint8_t minPixels, uint8_t maxPixels)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if ((minPixels < 1) || (minPixels > 100))
        return TcInvalidParam;

    if ((maxPixels < 1) || (maxPixels > 100))
        return TcInvalidParam;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 22;

    *( (uint8_t*)(tcBuffer + 1) ) = minPixels;
    *( (uint8_t*)(tcBuffer + 2) ) = maxPixels;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 3, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendsetTangentalDistortionGainsCmd(uint8_t nodeid, float p1, float p2)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 12;

    *( (float*)(tcBuffer + 1) ) = p1;
    *( (float*)(tcBuffer + 5) ) = p2;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 9, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendsetTimerTimeoutCmd(uint8_t nodeid, uint8_t timeout)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    if ((timeout < 1) || (timeout > 100))
        return TcInvalidParam;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 4;

    *( (uint8_t*)(tcBuffer + 1) ) = timeout;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 2, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendStreamDownImageCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 19;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendTestSRAMCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 34;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendTestWDGCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 35;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendTogglePowerSWCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 1;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendTriggerCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 38;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendUploadImageCmd(uint8_t nodeid)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 17;


    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 1, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}

CUBELIB_Result_t CUBESTAR3_SendWriteTo_IS_RegisterCmd(uint8_t nodeid, uint8_t reg, uint8_t dataH, uint8_t dataL)
{
    uint8_t* tcBuffer = cubeStar3CommsBuffer;
    I2C_TransferReturn_TypeDef i2cResult;

    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 13;

    *( (uint8_t*)(tcBuffer + 1) ) = reg;
    *( (uint8_t*)(tcBuffer + 2) ) = dataH;
    *( (uint8_t*)(tcBuffer + 3) ) = dataL;

    i2cResult = BSP_I2C_masterTransmit(BSP_I2C_SUB, nodeid, I2C_FLAG_WRITE, tcBuffer, 4, NULL, 0);
    if (i2cResult != i2cTransferDone)
        return i2cResult;

    return CubeLibOk;
}


