/************************************************************************************
 * This file was auto-generated by CIDEA                           .                *
 * Please do not modify the contents of this file manually.                         *
 ***********************************************************************************/


#include "cubeacp.h"

uint16_t CUBEACP_createTelemetryRequest(uint8_t* txBuffer, CUBEACP_Telemetry_t tlm)
{
  txBuffer[0] = tlm;

    switch(tlm)
    {
        case CubeAcp_AcpLoopState:
            return 3;
        case CubeAcp_ActuatorCmd:
            return 12;
        case CubeAcp_AdcsConfig:
            return 272;
        case CubeAcp_AdcsExecTimes:
            return 8;
        case CubeAcp_AdcsMeasure:
            return 72;
        case CubeAcp_AdcsMiscCurrents:
            return 6;
        case CubeAcp_AdcsPower:
            return 3;
        case CubeAcp_AdcsPowerMeasure:
            return 34;
        case CubeAcp_AdcsState:
            return 48;
        case CubeAcp_AdcsTemperatures1:
            return 6;
        case CubeAcp_AdcsTemperatures2:
            return 6;
        case CubeAcp_BlockChecksum:
            return 2;
        case CubeAcp_BootIndexStatus:
            return 2;
        case CubeAcp_Cache:
            return 1;
        case CubeAcp_CmdAttitude:
            return 6;
        case CubeAcp_CmdTrackingTarget:
            return 12;
        case CubeAcp_CoarseSunVec:
            return 6;
        case CubeAcp_CommsStatus:
            return 6;
        case CubeAcp_ConversionProgress:
            return 3;
        case CubeAcp_CubeACPState:
            return 1;
        case CubeAcp_CubeControlCurrents:
            return 6;
        case CubeAcp_CubeSenseCurrents:
            return 6;
        case CubeAcp_CurrentAdcsState:
            return 6;
        case CubeAcp_DownloadBlockReady:
            return 5;
        case CubeAcp_EdacErrors:
            return 6;
        case CubeAcp_EstimAttitude:
            return 6;
        case CubeAcp_EstimData:
            return 42;
        case CubeAcp_EstimGyroBias:
            return 6;
        case CubeAcp_EstimQuaternion:
            return 6;
        case CubeAcp_EstimRates:
            return 6;
        case CubeAcp_ExtendedIdentification:
            return 6;
        case CubeAcp_FileDownload:
            return 22;
        case CubeAcp_FileInfo:
            return 12;
        case CubeAcp_FineSunVec:
            return 6;
        case CubeAcp_HoleMap1:
            return 16;
        case CubeAcp_HoleMap2:
            return 16;
        case CubeAcp_HoleMap3:
            return 16;
        case CubeAcp_HoleMap4:
            return 16;
        case CubeAcp_HoleMap5:
            return 16;
        case CubeAcp_HoleMap6:
            return 16;
        case CubeAcp_HoleMap7:
            return 16;
        case CubeAcp_HoleMap8:
            return 16;
        case CubeAcp_Identification:
            return 8;
        case CubeAcp_ImageSaveStatus:
            return 2;
        case CubeAcp_InitializeUploadComplete:
            return 1;
        case CubeAcp_InnovationVec:
            return 6;
        case CubeAcp_LastLogEvent:
            return 6;
        case CubeAcp_LatchupErrors:
            return 6;
        case CubeAcp_LogSdConfig1:
            return 13;
        case CubeAcp_LogSdConfig2:
            return 13;
        case CubeAcp_LogUartConfig:
            return 12;
        case CubeAcp_MagField:
            return 6;
        case CubeAcp_MagTorquerCmd:
            return 6;
        case CubeAcp_ModelMagVec:
            return 6;
        case CubeAcp_ModelSunVec:
            return 6;
        case CubeAcp_NadirVec:
            return 6;
        case CubeAcp_OrbitParameters:
            return 64;
        case CubeAcp_PositionECEF:
            return 6;
        case CubeAcp_PositionECI:
            return 6;
        case CubeAcp_PositionLLH:
            return 6;
        case CubeAcp_QuaternionCovar:
            return 6;
        case CubeAcp_QuaternionErrVec:
            return 6;
        case CubeAcp_RateCovar:
            return 6;
        case CubeAcp_RateSensor:
            return 6;
        case CubeAcp_RawCam1Sens:
            return 6;
        case CubeAcp_RawCam2Sens:
            return 6;
        case CubeAcp_RawCss1:
            return 6;
        case CubeAcp_RawCss2:
            return 6;
        case CubeAcp_RawGPS:
            return 36;
        case CubeAcp_RawGpsStatus:
            return 6;
        case CubeAcp_RawGpsTime:
            return 6;
        case CubeAcp_RawGpsX:
            return 6;
        case CubeAcp_RawGpsY:
            return 6;
        case CubeAcp_RawGpsZ:
            return 6;
        case CubeAcp_RawMagnetometer:
            return 6;
        case CubeAcp_RawSensor:
            return 28;
        case CubeAcp_RawStarTracker:
            return 36;
        case CubeAcp_ReduntMagRaw:
            return 6;
        case CubeAcp_SpeedCmd:
            return 6;
        case CubeAcp_SramScrubSettings:
            return 2;
        case CubeAcp_Star1Body:
            return 6;
        case CubeAcp_Star1Orbit:
            return 6;
        case CubeAcp_Star1Raw:
            return 6;
        case CubeAcp_Star2Body:
            return 6;
        case CubeAcp_Star2Orbit:
            return 6;
        case CubeAcp_Star2Raw:
            return 6;
        case CubeAcp_Star3Body:
            return 6;
        case CubeAcp_Star3Orbit:
            return 6;
        case CubeAcp_Star3Raw:
            return 6;
        case CubeAcp_StarMagnitude:
            return 6;
        case CubeAcp_StarPerformance:
            return 6;
        case CubeAcp_StarTiming:
            return 6;
        case CubeAcp_TelecommandAcknowledge:
            return 4;
        case CubeAcp_UnixTime:
            return 6;
        case CubeAcp_UnixTimeSave:
            return 2;
        case CubeAcp_UploadBlockComplete:
            return 1;
        case CubeAcp_VelocityECI:
            return 6;
        case CubeAcp_WheelCurrents:
            return 6;
        case CubeAcp_WheelSpeed:
            return 6;
        default:
            return -1;
    }
}
CUBELIB_Result_t CUBEACP_AcpLoopStateTlm(uint8_t* rxBuffer, CUBEACP_AcpLoopState_t* returnVal)
{
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    returnVal->timeSinceLoopStart = *( (uint16_t*) (rxBuffer + 0) );

    enumVal = rxBuffer[2];
    returnVal->currentExecutionPoint = (CUBEACP_ExecutionWaypoints_t) enumVal;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_ActuatorCmdTlm(uint8_t* rxBuffer, CUBEACP_ActuatorCmd_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->torquerCmdX = *( (int16_t*) (rxBuffer + 0) );

    returnVal->torquerCmdY = *( (int16_t*) (rxBuffer + 2) );

    returnVal->torquerCmdZ = *( (int16_t*) (rxBuffer + 4) );

    returnVal->speedCmdX = *( (int16_t*) (rxBuffer + 6) );

    returnVal->speedCmdY = *( (int16_t*) (rxBuffer + 8) );

    returnVal->speedCmdZ = *( (int16_t*) (rxBuffer + 10) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_AdcsConfigTlm(uint8_t* rxBuffer, CUBEACP_AdcsConfig_t* returnVal)
{
    uint8_t rawCss1Scale;
    uint8_t rawCss2Scale;
    uint8_t rawCss3Scale;
    uint8_t rawCss4Scale;
    uint8_t rawCss5Scale;
    uint8_t rawCss6Scale;
    uint8_t rawCss7Scale;
    uint8_t rawCss8Scale;
    uint8_t rawCss9Scale;
    uint8_t rawCss10Scale;
    int16_t rawCam1Angle1;
    int16_t rawCam1Angle2;
    int16_t rawCam1Angle3;
    uint16_t rawCam1BoreX;
    uint16_t rawCam1BoreY;
    int16_t rawCam2Angle1;
    int16_t rawCam2Angle2;
    int16_t rawCam2Angle3;
    uint16_t rawCam2BoreX;
    uint16_t rawCam2BoreY;
    int16_t rawMagmAngle1;
    int16_t rawMagmAngle2;
    int16_t rawMagmAngle3;
    int16_t rawMagmOffset1;
    int16_t rawMagmOffset2;
    int16_t rawMagmOffset3;
    int16_t rawMagmSens11;
    int16_t rawMagmSens22;
    int16_t rawMagmSens33;
    int16_t rawMagmSens12;
    int16_t rawMagmSens13;
    int16_t rawMagmSens21;
    int16_t rawMagmSens23;
    int16_t rawMagmSens31;
    int16_t rawMagmSens32;
    int16_t rawXRateOffset;
    int16_t rawYRateOffset;
    int16_t rawZRateOffset;
    int16_t rawStarAngle1;
    int16_t rawStarAngle2;
    int16_t rawStarAngle3;
    uint8_t rawStarErrorMargin;
    uint16_t rawStarFocal;
    int16_t rawwy_ref;
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    enumVal = rxBuffer[0];
    returnVal->magtorq1 = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[1];
    returnVal->magtorq2 = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[2];
    returnVal->magtorq3 = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[3];
    returnVal->rW1Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[4];
    returnVal->rW2Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[5];
    returnVal->rW3Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[6];
    returnVal->rW4Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[7];
    returnVal->gyro1Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[8];
    returnVal->gyro2Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[9];
    returnVal->gyro3Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[10];
    returnVal->css1Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[11];
    returnVal->css2Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[12];
    returnVal->css3Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[13];
    returnVal->css4Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[14];
    returnVal->css5Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[15];
    returnVal->css6Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[16];
    returnVal->css7Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[17];
    returnVal->css8Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[18];
    returnVal->css9Conf = (CUBEACP_AxisSelect_t) enumVal;

    enumVal = rxBuffer[19];
    returnVal->css10Conf = (CUBEACP_AxisSelect_t) enumVal;

    rawCss1Scale = *( (uint8_t*) (rxBuffer + 20) );
    returnVal->css1Scale = rawCss1Scale*0.01;

    rawCss2Scale = *( (uint8_t*) (rxBuffer + 21) );
    returnVal->css2Scale = rawCss2Scale*0.01;

    rawCss3Scale = *( (uint8_t*) (rxBuffer + 22) );
    returnVal->css3Scale = rawCss3Scale*0.01;

    rawCss4Scale = *( (uint8_t*) (rxBuffer + 23) );
    returnVal->css4Scale = rawCss4Scale*0.01;

    rawCss5Scale = *( (uint8_t*) (rxBuffer + 24) );
    returnVal->css5Scale = rawCss5Scale*0.01;

    rawCss6Scale = *( (uint8_t*) (rxBuffer + 25) );
    returnVal->css6Scale = rawCss6Scale*0.01;

    rawCss7Scale = *( (uint8_t*) (rxBuffer + 26) );
    returnVal->css7Scale = rawCss7Scale*0.01;

    rawCss8Scale = *( (uint8_t*) (rxBuffer + 27) );
    returnVal->css8Scale = rawCss8Scale*0.01;

    rawCss9Scale = *( (uint8_t*) (rxBuffer + 28) );
    returnVal->css9Scale = rawCss9Scale*0.01;

    rawCss10Scale = *( (uint8_t*) (rxBuffer + 29) );
    returnVal->css10Scale = rawCss10Scale*0.01;

    returnVal->cssMinimum = *( (uint8_t*) (rxBuffer + 30) );

    rawCam1Angle1 = *( (int16_t*) (rxBuffer + 31) );
    returnVal->cam1Angle1 = rawCam1Angle1*0.01;

    rawCam1Angle2 = *( (int16_t*) (rxBuffer + 33) );
    returnVal->cam1Angle2 = rawCam1Angle2*0.01;

    rawCam1Angle3 = *( (int16_t*) (rxBuffer + 35) );
    returnVal->cam1Angle3 = rawCam1Angle3*0.01;

    returnVal->cam1Threshold = *( (uint8_t*) (rxBuffer + 37) );

    returnVal->cam1AutoAdj = (rxBuffer[38] & 0x01) >> 0;

    returnVal->cam1Exposure = *( (uint16_t*) (rxBuffer + 39) );

    rawCam1BoreX = *( (uint16_t*) (rxBuffer + 41) );
    returnVal->cam1BoreX = rawCam1BoreX*0.01;

    rawCam1BoreY = *( (uint16_t*) (rxBuffer + 43) );
    returnVal->cam1BoreY = rawCam1BoreY*0.01;

    returnVal->cam1Shift = (rxBuffer[45] & 0x01) >> 0;

    rawCam2Angle1 = *( (int16_t*) (rxBuffer + 46) );
    returnVal->cam2Angle1 = rawCam2Angle1*0.01;

    rawCam2Angle2 = *( (int16_t*) (rxBuffer + 48) );
    returnVal->cam2Angle2 = rawCam2Angle2*0.01;

    rawCam2Angle3 = *( (int16_t*) (rxBuffer + 50) );
    returnVal->cam2Angle3 = rawCam2Angle3*0.01;

    returnVal->cam2Threshold = *( (uint8_t*) (rxBuffer + 52) );

    returnVal->cam2AutoAdj = (rxBuffer[53] & 0x01) >> 0;

    returnVal->cam2Exposure = *( (uint16_t*) (rxBuffer + 54) );

    rawCam2BoreX = *( (uint16_t*) (rxBuffer + 56) );
    returnVal->cam2BoreX = rawCam2BoreX*0.01;

    rawCam2BoreY = *( (uint16_t*) (rxBuffer + 58) );
    returnVal->cam2BoreY = rawCam2BoreY*0.01;

    returnVal->cam2Shift = (rxBuffer[60] & 0x01) >> 0;

    returnVal->maskArea1Xmin = *( (uint16_t*) (rxBuffer + 61) );

    returnVal->maskArea1Xmax = *( (uint16_t*) (rxBuffer + 63) );

    returnVal->maskArea1Ymin = *( (uint16_t*) (rxBuffer + 65) );

    returnVal->maskArea1Ymax = *( (uint16_t*) (rxBuffer + 67) );

    returnVal->maskArea2Xmin = *( (uint16_t*) (rxBuffer + 69) );

    returnVal->maskArea2Xmax = *( (uint16_t*) (rxBuffer + 71) );

    returnVal->maskArea2Ymin = *( (uint16_t*) (rxBuffer + 73) );

    returnVal->maskArea2Ymax = *( (uint16_t*) (rxBuffer + 75) );

    returnVal->maskArea3Xmin = *( (uint16_t*) (rxBuffer + 77) );

    returnVal->maskArea3Xmax = *( (uint16_t*) (rxBuffer + 79) );

    returnVal->maskArea3Ymin = *( (uint16_t*) (rxBuffer + 81) );

    returnVal->maskArea3Ymax = *( (uint16_t*) (rxBuffer + 83) );

    returnVal->maskArea4Xmin = *( (uint16_t*) (rxBuffer + 85) );

    returnVal->maskArea4Xmax = *( (uint16_t*) (rxBuffer + 87) );

    returnVal->maskArea4Ymin = *( (uint16_t*) (rxBuffer + 89) );

    returnVal->maskArea4Ymax = *( (uint16_t*) (rxBuffer + 91) );

    returnVal->maskArea5Xmin = *( (uint16_t*) (rxBuffer + 93) );

    returnVal->maskArea5Xmax = *( (uint16_t*) (rxBuffer + 95) );

    returnVal->maskArea5Ymin = *( (uint16_t*) (rxBuffer + 97) );

    returnVal->maskArea5Ymax = *( (uint16_t*) (rxBuffer + 99) );

    rawMagmAngle1 = *( (int16_t*) (rxBuffer + 101) );
    returnVal->magmAngle1 = rawMagmAngle1*0.01;

    rawMagmAngle2 = *( (int16_t*) (rxBuffer + 103) );
    returnVal->magmAngle2 = rawMagmAngle2*0.01;

    rawMagmAngle3 = *( (int16_t*) (rxBuffer + 105) );
    returnVal->magmAngle3 = rawMagmAngle3*0.01;

    rawMagmOffset1 = *( (int16_t*) (rxBuffer + 107) );
    returnVal->magmOffset1 = rawMagmOffset1*0.001;

    rawMagmOffset2 = *( (int16_t*) (rxBuffer + 109) );
    returnVal->magmOffset2 = rawMagmOffset2*0.001;

    rawMagmOffset3 = *( (int16_t*) (rxBuffer + 111) );
    returnVal->magmOffset3 = rawMagmOffset3*0.001;

    rawMagmSens11 = *( (int16_t*) (rxBuffer + 113) );
    returnVal->magmSens11 = rawMagmSens11*0.001;

    rawMagmSens22 = *( (int16_t*) (rxBuffer + 115) );
    returnVal->magmSens22 = rawMagmSens22*0.001;

    rawMagmSens33 = *( (int16_t*) (rxBuffer + 117) );
    returnVal->magmSens33 = rawMagmSens33*0.001;

    rawMagmSens12 = *( (int16_t*) (rxBuffer + 119) );
    returnVal->magmSens12 = rawMagmSens12*0.001;

    rawMagmSens13 = *( (int16_t*) (rxBuffer + 121) );
    returnVal->magmSens13 = rawMagmSens13*0.001;

    rawMagmSens21 = *( (int16_t*) (rxBuffer + 123) );
    returnVal->magmSens21 = rawMagmSens21*0.001;

    rawMagmSens23 = *( (int16_t*) (rxBuffer + 125) );
    returnVal->magmSens23 = rawMagmSens23*0.001;

    rawMagmSens31 = *( (int16_t*) (rxBuffer + 127) );
    returnVal->magmSens31 = rawMagmSens31*0.001;

    rawMagmSens32 = *( (int16_t*) (rxBuffer + 129) );
    returnVal->magmSens32 = rawMagmSens32*0.001;

    rawXRateOffset = *( (int16_t*) (rxBuffer + 131) );
    returnVal->xRateOffset = rawXRateOffset*0.001;

    rawYRateOffset = *( (int16_t*) (rxBuffer + 133) );
    returnVal->yRateOffset = rawYRateOffset*0.001;

    rawZRateOffset = *( (int16_t*) (rxBuffer + 135) );
    returnVal->zRateOffset = rawZRateOffset*0.001;

    returnVal->rateSensorMult = *( (uint8_t*) (rxBuffer + 137) );

    rawStarAngle1 = *( (int16_t*) (rxBuffer + 138) );
    returnVal->starAngle1 = rawStarAngle1*0.01;

    rawStarAngle2 = *( (int16_t*) (rxBuffer + 140) );
    returnVal->starAngle2 = rawStarAngle2*0.01;

    rawStarAngle3 = *( (int16_t*) (rxBuffer + 142) );
    returnVal->starAngle3 = rawStarAngle3*0.01;

    returnVal->starExposure = *( (uint16_t*) (rxBuffer + 144) );

    returnVal->detectionThreshold = *( (uint8_t*) (rxBuffer + 146) );

    returnVal->starThreshold = *( (uint8_t*) (rxBuffer + 147) );

    returnVal->maxStarMatched = *( (uint8_t*) (rxBuffer + 148) );

    returnVal->maxStarPixel = *( (uint8_t*) (rxBuffer + 149) );

    returnVal->maxStarNoise = *( (uint8_t*) (rxBuffer + 150) );

    returnVal->minStarPixel = *( (uint8_t*) (rxBuffer + 151) );

    rawStarErrorMargin = *( (uint8_t*) (rxBuffer + 152) );
    returnVal->starErrorMargin = rawStarErrorMargin*0.01;

    returnVal->starCentX = *((float*)(rxBuffer + 153));

    returnVal->starCentY = *((float*)(rxBuffer + 157));

    rawStarFocal = *( (uint16_t*) (rxBuffer + 161) );
    returnVal->starFocal = rawStarFocal*0.0001;

    returnVal->syncDelay = *( (uint8_t*) (rxBuffer + 163) );

    returnVal->ks = *((float*)(rxBuffer + 164));

    returnVal->kd = *((float*)(rxBuffer + 168));

    rawwy_ref = *( (int16_t*) (rxBuffer + 172) );
    returnVal->wy_ref = rawwy_ref*0.001;

    returnVal->kdf = *((float*)(rxBuffer + 174));

    returnVal->kh = *((float*)(rxBuffer + 178));

    returnVal->kn = *((float*)(rxBuffer + 182));

    returnVal->kp1 = *((float*)(rxBuffer + 186));

    returnVal->kd1 = *((float*)(rxBuffer + 190));

    returnVal->h_ref = *((float*)(rxBuffer + 194));

    returnVal->kp2 = *((float*)(rxBuffer + 198));

    returnVal->kd2 = *((float*)(rxBuffer + 202));

    returnVal->kp3 = *((float*)(rxBuffer + 206));

    returnVal->kd3 = *((float*)(rxBuffer + 210));

    returnVal->ki3 = *((float*)(rxBuffer + 214));

    returnVal->ixx = *((float*)(rxBuffer + 218));

    returnVal->iyy = *((float*)(rxBuffer + 222));

    returnVal->izz = *((float*)(rxBuffer + 226));

    returnVal->ixy = *((float*)(rxBuffer + 230));

    returnVal->ixz = *((float*)(rxBuffer + 234));

    returnVal->iyz = *((float*)(rxBuffer + 238));

    returnVal->magRateNoise = *((float*)(rxBuffer + 242));

    returnVal->ekfSysNoise = *((float*)(rxBuffer + 246));

    returnVal->cssNoise = *((float*)(rxBuffer + 250));

    returnVal->sunNoise = *((float*)(rxBuffer + 254));

    returnVal->nadirNoise = *((float*)(rxBuffer + 258));

    returnVal->magNoise = *((float*)(rxBuffer + 262));

    returnVal->starNoise = *((float*)(rxBuffer + 266));

    returnVal->useSunEst = (rxBuffer[270] & 0x01) >> 0;

    returnVal->useNadirEst = (rxBuffer[270] & 0x02) >> 1;

    returnVal->useCssEst = (rxBuffer[270] & 0x04) >> 2;

    returnVal->useStarEst = (rxBuffer[270] & 0x08) >> 3;

    enumVal = (rxBuffer[270] >> 4) & 3;
    returnVal->magMode = (CUBEACP_MagModeVal_t) enumVal;

    returnVal->cam1Cam2Period = *( (uint8_t*) (rxBuffer + 271) );

    if ((returnVal->starCentX < -5000) || (returnVal->starCentX > 5000))
        return TlmRangeError;

    if ((returnVal->starCentY < -5000) || (returnVal->starCentY > 5000))
        return TlmRangeError;

    if ((returnVal->ks < 0) || (returnVal->ks > 10000))
        return TlmRangeError;

    if ((returnVal->kd < 0) || (returnVal->kd > 10000))
        return TlmRangeError;

    if ((returnVal->wy_ref < -100000) || (returnVal->wy_ref > 0))
        return TlmRangeError;

    if ((returnVal->kdf < 0) || (returnVal->kdf > 100))
        return TlmRangeError;

    if ((returnVal->kh < 0) || (returnVal->kh > 10000))
        return TlmRangeError;

    if ((returnVal->kn < 0) || (returnVal->kn > 10000))
        return TlmRangeError;

    if ((returnVal->kp1 < 0) || (returnVal->kp1 > 100))
        return TlmRangeError;

    if ((returnVal->kd1 < 0) || (returnVal->kd1 > 100))
        return TlmRangeError;

    if ((returnVal->h_ref < -10) || (returnVal->h_ref > 0))
        return TlmRangeError;

    if ((returnVal->kp2 < 0) || (returnVal->kp2 > 100))
        return TlmRangeError;

    if ((returnVal->kd2 < 0) || (returnVal->kd2 > 100))
        return TlmRangeError;

    if ((returnVal->kp3 < 0) || (returnVal->kp3 > 100))
        return TlmRangeError;

    if ((returnVal->kd3 < 0) || (returnVal->kd3 > 100))
        return TlmRangeError;

    if ((returnVal->ki3 < 0) || (returnVal->ki3 > 100))
        return TlmRangeError;

    if ((returnVal->ixx < 0) || (returnVal->ixx > 10))
        return TlmRangeError;

    if ((returnVal->iyy < 0) || (returnVal->iyy > 10))
        return TlmRangeError;

    if ((returnVal->izz < 0) || (returnVal->izz > 10))
        return TlmRangeError;

    if ((returnVal->ixy < -10) || (returnVal->ixy > 10))
        return TlmRangeError;

    if ((returnVal->ixz < -10) || (returnVal->ixz > 10))
        return TlmRangeError;

    if ((returnVal->iyz < -10) || (returnVal->iyz > 10))
        return TlmRangeError;

    if ((returnVal->magRateNoise < 0) || (returnVal->magRateNoise > 100))
        return TlmRangeError;

    if ((returnVal->ekfSysNoise < 0) || (returnVal->ekfSysNoise > 100))
        return TlmRangeError;

    if ((returnVal->cssNoise < 0) || (returnVal->cssNoise > 100))
        return TlmRangeError;

    if ((returnVal->sunNoise < 0) || (returnVal->sunNoise > 100))
        return TlmRangeError;

    if ((returnVal->nadirNoise < 0) || (returnVal->nadirNoise > 100))
        return TlmRangeError;

    if ((returnVal->magNoise < 0) || (returnVal->magNoise > 100))
        return TlmRangeError;

    if ((returnVal->starNoise < 0) || (returnVal->starNoise > 100))
        return TlmRangeError;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_AdcsExecTimesTlm(uint8_t* rxBuffer, CUBEACP_AdcsExecTimes_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->timeAdcsUpdate = *( (uint16_t*) (rxBuffer + 0) );

    returnVal->timeSensorActuatorComms = *( (uint16_t*) (rxBuffer + 2) );

    returnVal->timeSgp4 = *( (uint16_t*) (rxBuffer + 4) );

    returnVal->timeIgrf = *( (uint16_t*) (rxBuffer + 6) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_AdcsMeasureTlm(uint8_t* rxBuffer, CUBEACP_AdcsMeasure_t* returnVal)
{
    int16_t rawMagX;
    int16_t rawMagY;
    int16_t rawMagZ;
    int16_t rawCssX;
    int16_t rawCssY;
    int16_t rawCssZ;
    int16_t rawSunX;
    int16_t rawSunY;
    int16_t rawSunZ;
    int16_t rawNadirX;
    int16_t rawNadirY;
    int16_t rawNadirZ;
    int16_t rawRateX;
    int16_t rawRateY;
    int16_t rawRateZ;
    int16_t rawStar1BX;
    int16_t rawStar1BY;
    int16_t rawStar1BZ;
    int16_t rawStar1OX;
    int16_t rawStar1OY;
    int16_t rawStar1OZ;
    int16_t rawStar2BX;
    int16_t rawStar2BY;
    int16_t rawStar2BZ;
    int16_t rawStar2OX;
    int16_t rawStar2OY;
    int16_t rawStar2OZ;
    int16_t rawStar3BX;
    int16_t rawStar3BY;
    int16_t rawStar3BZ;
    int16_t rawStar3OX;
    int16_t rawStar3OY;
    int16_t rawStar3OZ;
    if (returnVal == 0)
        return PointerIsNull;

    rawMagX = *( (int16_t*) (rxBuffer + 0) );
    returnVal->magX = rawMagX*0.01;

    rawMagY = *( (int16_t*) (rxBuffer + 2) );
    returnVal->magY = rawMagY*0.01;

    rawMagZ = *( (int16_t*) (rxBuffer + 4) );
    returnVal->magZ = rawMagZ*0.01;

    rawCssX = *( (int16_t*) (rxBuffer + 6) );
    returnVal->cssX = rawCssX/10000.0;

    rawCssY = *( (int16_t*) (rxBuffer + 8) );
    returnVal->cssY = rawCssY/10000.0;

    rawCssZ = *( (int16_t*) (rxBuffer + 10) );
    returnVal->cssZ = rawCssZ/10000.0;

    rawSunX = *( (int16_t*) (rxBuffer + 12) );
    returnVal->sunX = rawSunX/10000.0;

    rawSunY = *( (int16_t*) (rxBuffer + 14) );
    returnVal->sunY = rawSunY/10000.0;

    rawSunZ = *( (int16_t*) (rxBuffer + 16) );
    returnVal->sunZ = rawSunZ/10000.0;

    rawNadirX = *( (int16_t*) (rxBuffer + 18) );
    returnVal->nadirX = rawNadirX/10000.0;

    rawNadirY = *( (int16_t*) (rxBuffer + 20) );
    returnVal->nadirY = rawNadirY/10000.0;

    rawNadirZ = *( (int16_t*) (rxBuffer + 22) );
    returnVal->nadirZ = rawNadirZ/10000.0;

    rawRateX = *( (int16_t*) (rxBuffer + 24) );
    returnVal->rateX = rawRateX*0.01;

    rawRateY = *( (int16_t*) (rxBuffer + 26) );
    returnVal->rateY = rawRateY*0.01;

    rawRateZ = *( (int16_t*) (rxBuffer + 28) );
    returnVal->rateZ = rawRateZ*0.01;

    returnVal->speedX = *( (int16_t*) (rxBuffer + 30) );

    returnVal->speedY = *( (int16_t*) (rxBuffer + 32) );

    returnVal->speedZ = *( (int16_t*) (rxBuffer + 34) );

    rawStar1BX = *( (int16_t*) (rxBuffer + 36) );
    returnVal->star1BX = rawStar1BX/10000.0;

    rawStar1BY = *( (int16_t*) (rxBuffer + 38) );
    returnVal->star1BY = rawStar1BY/10000.0;

    rawStar1BZ = *( (int16_t*) (rxBuffer + 40) );
    returnVal->star1BZ = rawStar1BZ/10000.0;

    rawStar1OX = *( (int16_t*) (rxBuffer + 42) );
    returnVal->star1OX = rawStar1OX/10000.0;

    rawStar1OY = *( (int16_t*) (rxBuffer + 44) );
    returnVal->star1OY = rawStar1OY/10000.0;

    rawStar1OZ = *( (int16_t*) (rxBuffer + 46) );
    returnVal->star1OZ = rawStar1OZ/10000.0;

    rawStar2BX = *( (int16_t*) (rxBuffer + 48) );
    returnVal->star2BX = rawStar2BX/10000.0;

    rawStar2BY = *( (int16_t*) (rxBuffer + 50) );
    returnVal->star2BY = rawStar2BY/10000.0;

    rawStar2BZ = *( (int16_t*) (rxBuffer + 52) );
    returnVal->star2BZ = rawStar2BZ/10000.0;

    rawStar2OX = *( (int16_t*) (rxBuffer + 54) );
    returnVal->star2OX = rawStar2OX/10000.0;

    rawStar2OY = *( (int16_t*) (rxBuffer + 56) );
    returnVal->star2OY = rawStar2OY/10000.0;

    rawStar2OZ = *( (int16_t*) (rxBuffer + 58) );
    returnVal->star2OZ = rawStar2OZ/10000.0;

    rawStar3BX = *( (int16_t*) (rxBuffer + 60) );
    returnVal->star3BX = rawStar3BX/10000.0;

    rawStar3BY = *( (int16_t*) (rxBuffer + 62) );
    returnVal->star3BY = rawStar3BY/10000.0;

    rawStar3BZ = *( (int16_t*) (rxBuffer + 64) );
    returnVal->star3BZ = rawStar3BZ/10000.0;

    rawStar3OX = *( (int16_t*) (rxBuffer + 66) );
    returnVal->star3OX = rawStar3OX/10000.0;

    rawStar3OY = *( (int16_t*) (rxBuffer + 68) );
    returnVal->star3OY = rawStar3OY/10000.0;

    rawStar3OZ = *( (int16_t*) (rxBuffer + 70) );
    returnVal->star3OZ = rawStar3OZ/10000.0;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_AdcsMiscCurrentsTlm(uint8_t* rxBuffer, CUBEACP_AdcsMiscCurrents_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_AdcsPowerTlm(uint8_t* rxBuffer, CUBEACP_AdcsPower_t* returnVal)
{
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    enumVal = (rxBuffer[0] >> 0) & 3;
    returnVal->cubeControlSignalPower = (CUBEACP_PowerSelect_t) enumVal;

    enumVal = (rxBuffer[0] >> 2) & 3;
    returnVal->cubeControlMotorPower = (CUBEACP_PowerSelect_t) enumVal;

    enumVal = (rxBuffer[0] >> 4) & 3;
    returnVal->cubeSensePower = (CUBEACP_PowerSelect_t) enumVal;

    enumVal = (rxBuffer[0] >> 6) & 3;
    returnVal->cubeStarPower = (CUBEACP_PowerSelect_t) enumVal;

    enumVal = (rxBuffer[1] >> 0) & 3;
    returnVal->cubeWheel1Power = (CUBEACP_PowerSelect_t) enumVal;

    enumVal = (rxBuffer[1] >> 2) & 3;
    returnVal->cubeWheel2Power = (CUBEACP_PowerSelect_t) enumVal;

    enumVal = (rxBuffer[1] >> 4) & 3;
    returnVal->cubeWheel3Power = (CUBEACP_PowerSelect_t) enumVal;

    enumVal = (rxBuffer[1] >> 6) & 3;
    returnVal->motorPower = (CUBEACP_PowerSelect_t) enumVal;

    enumVal = (rxBuffer[2] >> 0) & 3;
    returnVal->gpsLnaPower = (CUBEACP_PowerSelect_t) enumVal;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_AdcsPowerMeasureTlm(uint8_t* rxBuffer, CUBEACP_AdcsPowerMeasure_t* returnVal)
{
    uint16_t rawCubeSense3V3Current;
    uint16_t rawCubeSenseCam2Current;
    uint16_t rawCubeSenseCam1Current;
    uint16_t rawCubeControl3V3Current;
    uint16_t rawCubeControl5VCurrent;
    uint16_t rawCubeControlBatCurrent;
    uint16_t rawWheel1Current;
    uint16_t rawWheel2Current;
    uint16_t rawWheel3Current;
    uint16_t rawCubeStarCurrent;
    uint16_t rawMagtorqCurrent;
    int16_t rawMagnetometerTemp;
    int16_t rawRedundentMagnetometerTemp;
    if (returnVal == 0)
        return PointerIsNull;

    rawCubeSense3V3Current = *( (uint16_t*) (rxBuffer + 0) );
    returnVal->cubeSense3V3Current = rawCubeSense3V3Current*0.1;

    rawCubeSenseCam2Current = *( (uint16_t*) (rxBuffer + 2) );
    returnVal->cubeSenseCam2Current = rawCubeSenseCam2Current*0.1;

    rawCubeSenseCam1Current = *( (uint16_t*) (rxBuffer + 4) );
    returnVal->cubeSenseCam1Current = rawCubeSenseCam1Current*0.1;

    rawCubeControl3V3Current = *( (uint16_t*) (rxBuffer + 6) );
    returnVal->cubeControl3V3Current = rawCubeControl3V3Current*0.48828125;

    rawCubeControl5VCurrent = *( (uint16_t*) (rxBuffer + 8) );
    returnVal->cubeControl5VCurrent = rawCubeControl5VCurrent*0.48828125;

    rawCubeControlBatCurrent = *( (uint16_t*) (rxBuffer + 10) );
    returnVal->cubeControlBatCurrent = rawCubeControlBatCurrent*0.48828125;

    rawWheel1Current = *( (uint16_t*) (rxBuffer + 12) );
    returnVal->wheel1Current = rawWheel1Current*0.01;

    rawWheel2Current = *( (uint16_t*) (rxBuffer + 14) );
    returnVal->wheel2Current = rawWheel2Current*0.01;

    rawWheel3Current = *( (uint16_t*) (rxBuffer + 16) );
    returnVal->wheel3Current = rawWheel3Current*0.01;

    rawCubeStarCurrent = *( (uint16_t*) (rxBuffer + 18) );
    returnVal->cubeStarCurrent = rawCubeStarCurrent*0.01;

    rawMagtorqCurrent = *( (uint16_t*) (rxBuffer + 20) );
    returnVal->magtorqCurrent = rawMagtorqCurrent*0.1;

    returnVal->mCUTemp = *( (int16_t*) (rxBuffer + 22) );

    rawMagnetometerTemp = *( (int16_t*) (rxBuffer + 24) );
    returnVal->magnetometerTemp = rawMagnetometerTemp/10.0;

    rawRedundentMagnetometerTemp = *( (int16_t*) (rxBuffer + 26) );
    returnVal->redundentMagnetometerTemp = rawRedundentMagnetometerTemp/10.0;

    returnVal->xRateTemp = *( (int16_t*) (rxBuffer + 28) );

    returnVal->yRateTemp = *( (int16_t*) (rxBuffer + 30) );

    returnVal->zRateTemp = *( (int16_t*) (rxBuffer + 32) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_AdcsStateTlm(uint8_t* rxBuffer, CUBEACP_AdcsState_t* returnVal)
{
    int16_t rawRoll;
    int16_t rawPitch;
    int16_t rawYaw;
    int16_t rawRateX;
    int16_t rawRateY;
    int16_t rawRateZ;
    int16_t rawPositionX;
    int16_t rawPositionY;
    int16_t rawPositionZ;
    int16_t rawVelocityX;
    int16_t rawVelocityY;
    int16_t rawVelocityZ;
    int16_t rawLatitude;
    int16_t rawLongitude;
    uint16_t rawAltitude;
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    enumVal = (rxBuffer[0] >> 0) & 15;
    returnVal->estimMode = (CUBEACP_EstimModeSelect_t) enumVal;

    enumVal = (rxBuffer[0] >> 4) & 15;
    returnVal->controlMode = (CUBEACP_ConModeSelect_t) enumVal;

    enumVal = (rxBuffer[1] >> 0) & 3;
    returnVal->adcsRunMode = (CUBEACP_AdcsRunMode_t) enumVal;

    returnVal->cubeControlSignalPower = (rxBuffer[1] & 0x04) >> 2;

    returnVal->cubeControlMotorPower = (rxBuffer[1] & 0x08) >> 3;

    returnVal->cubeSensePower = (rxBuffer[1] & 0x10) >> 4;

    returnVal->cubeWheel1Power = (rxBuffer[1] & 0x20) >> 5;

    returnVal->cubeWheel2Power = (rxBuffer[1] & 0x40) >> 6;

    returnVal->cubeWheel3Power = (rxBuffer[1] & 0x80) >> 7;

    returnVal->cubeStarPower = (rxBuffer[2] & 0x01) >> 0;

    returnVal->gpsReceiverPower = (rxBuffer[2] & 0x02) >> 1;

    returnVal->gpsLnaPower = (rxBuffer[2] & 0x04) >> 2;

    returnVal->motorDriverPower = (rxBuffer[2] & 0x08) >> 3;

    returnVal->sunAboveHorizon = (rxBuffer[2] & 0x10) >> 4;

    returnVal->cubeSenseCommsError = (rxBuffer[2] & 0x20) >> 5;

    returnVal->cubeControlSignalCommsError = (rxBuffer[2] & 0x40) >> 6;

    returnVal->cubeControlMotorCommsError = (rxBuffer[2] & 0x80) >> 7;

    returnVal->cubeWheel1CommsError = (rxBuffer[3] & 0x01) >> 0;

    returnVal->cubeWheel2CommsError = (rxBuffer[3] & 0x02) >> 1;

    returnVal->cubeWheel3CommsError = (rxBuffer[3] & 0x04) >> 2;

    returnVal->cubeStarCommsError = (rxBuffer[3] & 0x08) >> 3;

    returnVal->magRangeError = (rxBuffer[3] & 0x10) >> 4;

    returnVal->cam1SensOvercurrent = (rxBuffer[3] & 0x20) >> 5;

    returnVal->cam1SensNotIdle = (rxBuffer[3] & 0x40) >> 6;

    returnVal->cam1SensDetectError = (rxBuffer[3] & 0x80) >> 7;

    returnVal->sunSensRangeError = (rxBuffer[4] & 0x01) >> 0;

    returnVal->cam2SensOvercurrent = (rxBuffer[4] & 0x02) >> 1;

    returnVal->cam2SensNotIdle = (rxBuffer[4] & 0x04) >> 2;

    returnVal->cam2SensDetectError = (rxBuffer[4] & 0x08) >> 3;

    returnVal->nadirSensRangeError = (rxBuffer[4] & 0x10) >> 4;

    returnVal->rateSensRangeError = (rxBuffer[4] & 0x20) >> 5;

    returnVal->wheelSpeedRangeError = (rxBuffer[4] & 0x40) >> 6;

    returnVal->cssError = (rxBuffer[4] & 0x80) >> 7;

    returnVal->starMatchError = (rxBuffer[5] & 0x01) >> 0;

    returnVal->starTrackOvercurrent = (rxBuffer[5] & 0x02) >> 1;

    returnVal->orbitParamsInvalidError = (rxBuffer[5] & 0x04) >> 2;

    returnVal->configInvalidError = (rxBuffer[5] & 0x08) >> 3;

    returnVal->controlModeNotAllowed = (rxBuffer[5] & 0x10) >> 4;

    returnVal->estimatorNotAllowed = (rxBuffer[5] & 0x20) >> 5;

    returnVal->magfieldModelError = (rxBuffer[5] & 0x40) >> 6;

    returnVal->nodeRecoveryError = (rxBuffer[5] & 0x80) >> 7;

    rawRoll = *( (int16_t*) (rxBuffer + 6) );
    returnVal->roll = rawRoll*0.01;

    rawPitch = *( (int16_t*) (rxBuffer + 8) );
    returnVal->pitch = rawPitch*0.01;

    rawYaw = *( (int16_t*) (rxBuffer + 10) );
    returnVal->yaw = rawYaw*0.01;

    returnVal->q1 = *( (int16_t*) (rxBuffer + 12) );

    returnVal->q2 = *( (int16_t*) (rxBuffer + 14) );

    returnVal->q3 = *( (int16_t*) (rxBuffer + 16) );

    rawRateX = *( (int16_t*) (rxBuffer + 18) );
    returnVal->rateX = rawRateX*0.01;

    rawRateY = *( (int16_t*) (rxBuffer + 20) );
    returnVal->rateY = rawRateY*0.01;

    rawRateZ = *( (int16_t*) (rxBuffer + 22) );
    returnVal->rateZ = rawRateZ*0.01;

    rawPositionX = *( (int16_t*) (rxBuffer + 24) );
    returnVal->positionX = rawPositionX*0.25;

    rawPositionY = *( (int16_t*) (rxBuffer + 26) );
    returnVal->positionY = rawPositionY*0.25;

    rawPositionZ = *( (int16_t*) (rxBuffer + 28) );
    returnVal->positionZ = rawPositionZ*0.25;

    rawVelocityX = *( (int16_t*) (rxBuffer + 30) );
    returnVal->velocityX = rawVelocityX*0.25;

    rawVelocityY = *( (int16_t*) (rxBuffer + 32) );
    returnVal->velocityY = rawVelocityY*0.25;

    rawVelocityZ = *( (int16_t*) (rxBuffer + 34) );
    returnVal->velocityZ = rawVelocityZ*0.25;

    rawLatitude = *( (int16_t*) (rxBuffer + 36) );
    returnVal->latitude = rawLatitude*0.01;

    rawLongitude = *( (int16_t*) (rxBuffer + 38) );
    returnVal->longitude = rawLongitude*0.01;

    rawAltitude = *( (uint16_t*) (rxBuffer + 40) );
    returnVal->altitude = rawAltitude*0.01;

    returnVal->posEcefX = *( (int16_t*) (rxBuffer + 42) );

    returnVal->posEcefY = *( (int16_t*) (rxBuffer + 44) );

    returnVal->posEcefZ = *( (int16_t*) (rxBuffer + 46) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_AdcsTemperatures1Tlm(uint8_t* rxBuffer, CUBEACP_AdcsTemperatures1_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_AdcsTemperatures2Tlm(uint8_t* rxBuffer, CUBEACP_AdcsTemperatures2_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_BlockChecksumTlm(uint8_t* rxBuffer, uint16_t* checksum)
{
    if (checksum == 0)
        return PointerIsNull;

    *checksum = *( (uint16_t*) (rxBuffer + 0) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_BootIndexStatusTlm(uint8_t* rxBuffer, CUBEACP_BootIndexStatus_t* returnVal)
{
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    enumVal = rxBuffer[0];
    returnVal->programIndex = (CUBEACP_BootProgramsList_t) enumVal;

    enumVal = rxBuffer[1];
    returnVal->bootStatus = (CUBEACP_BootStatus_t) enumVal;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_CacheTlm(uint8_t* rxBuffer, bool* enabled)
{
    if (enabled == 0)
        return PointerIsNull;

    *enabled = (rxBuffer[0] & 0x01) >> 0;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_CmdAttitudeTlm(uint8_t* rxBuffer, CUBEACP_CmdAttitude_t* returnVal)
{
    int16_t rawRoll;
    int16_t rawPitch;
    int16_t rawYaw;
    if (returnVal == 0)
        return PointerIsNull;

    rawRoll = *( (int16_t*) (rxBuffer + 0) );
    returnVal->roll = rawRoll*0.01;

    rawPitch = *( (int16_t*) (rxBuffer + 2) );
    returnVal->pitch = rawPitch*0.01;

    rawYaw = *( (int16_t*) (rxBuffer + 4) );
    returnVal->yaw = rawYaw*0.01;

    if ((returnVal->roll < -9000) || (returnVal->roll > 9000))
        return TlmRangeError;

    if ((returnVal->pitch < -18000) || (returnVal->pitch > 18000))
        return TlmRangeError;

    if ((returnVal->yaw < -18000) || (returnVal->yaw > 18000))
        return TlmRangeError;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_CmdTrackingTargetTlm(uint8_t* rxBuffer, CUBEACP_CmdTrackingTarget_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->longRef = *((float*)(rxBuffer + 0));

    returnVal->latRef = *((float*)(rxBuffer + 4));

    returnVal->altRef = *((float*)(rxBuffer + 8));

    if ((returnVal->longRef < 0) || (returnVal->longRef > 360))
        return TlmRangeError;

    if ((returnVal->latRef < -90) || (returnVal->latRef > 90))
        return TlmRangeError;

    if ((returnVal->altRef < -20000) || (returnVal->altRef > 20000))
        return TlmRangeError;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_CoarseSunVecTlm(uint8_t* rxBuffer, CUBEACP_CoarseSunVec_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_CommsStatusTlm(uint8_t* rxBuffer, CUBEACP_CommsStatus_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->tcCounter = *( (uint16_t*) (rxBuffer + 0) );

    returnVal->tlmCounter = *( (uint16_t*) (rxBuffer + 2) );

    returnVal->uartBufferOverrun = (rxBuffer[4] & 0x01) >> 0;

    returnVal->uartProtocolError = (rxBuffer[4] & 0x02) >> 1;

    returnVal->uartMsgIncomplete = (rxBuffer[4] & 0x04) >> 2;

    returnVal->i2CTelemetryError = (rxBuffer[4] & 0x08) >> 3;

    returnVal->i2CBufferError = (rxBuffer[4] & 0x10) >> 4;

    returnVal->cANBufferError = (rxBuffer[4] & 0x20) >> 5;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_ConversionProgressTlm(uint8_t* rxBuffer, CUBEACP_ConversionProgress_t* returnVal)
{
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    returnVal->progress = *( (uint8_t*) (rxBuffer + 0) );

    enumVal = rxBuffer[1];
    returnVal->conversionResult = (CUBEACP_JpgConvertResult_t) enumVal;

    returnVal->outFileCounter = *( (uint8_t*) (rxBuffer + 2) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_CubeACPStateTlm(uint8_t* rxBuffer, CUBEACP_CubeACPState_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->adcsConfigLoadError = (rxBuffer[0] & 0x01) >> 0;

    returnVal->orbitParamsLoadError = (rxBuffer[0] & 0x02) >> 1;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_CubeControlCurrentsTlm(uint8_t* rxBuffer, CUBEACP_CubeControlCurrents_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_CubeSenseCurrentsTlm(uint8_t* rxBuffer, CUBEACP_CubeSenseCurrents_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_CurrentAdcsStateTlm(uint8_t* rxBuffer, CUBEACP_CurrentAdcsState_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_DownloadBlockReadyTlm(uint8_t* rxBuffer, CUBEACP_DownloadBlockReady_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->ready = (rxBuffer[0] & 0x01) >> 0;

    returnVal->parameterError = (rxBuffer[0] & 0x02) >> 1;

    returnVal->checksum = *( (uint16_t*) (rxBuffer + 1) );

    returnVal->length = *( (uint16_t*) (rxBuffer + 3) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_EdacErrorsTlm(uint8_t* rxBuffer, CUBEACP_EdacErrors_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->singleSRAMSEUs = *( (uint16_t*) (rxBuffer + 0) );

    returnVal->doubleSRAMSEUs = *( (uint16_t*) (rxBuffer + 2) );

    returnVal->multiSRAMSEUs = *( (uint16_t*) (rxBuffer + 4) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_EstimAttitudeTlm(uint8_t* rxBuffer, CUBEACP_EstimAttitude_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_EstimDataTlm(uint8_t* rxBuffer, CUBEACP_EstimData_t* returnVal)
{
    int16_t rawIgrfMagX;
    int16_t rawIgrfMagY;
    int16_t rawIgrfMagZ;
    int16_t rawModelSunX;
    int16_t rawModelSunY;
    int16_t rawModelSunZ;
    int16_t rawEstimGyroBiasX;
    int16_t rawEstimGyroBiasY;
    int16_t rawEstimGyroBiasZ;
    int16_t rawInnovX;
    int16_t rawInnovY;
    int16_t rawInnovZ;
    int16_t rawQError1;
    int16_t rawQError2;
    int16_t rawQError3;
    int16_t rawQCovar1;
    int16_t rawQCovar2;
    int16_t rawQCovar3;
    int16_t rawRateCovarX;
    int16_t rawRateCovarY;
    int16_t rawRateCovarZ;
    if (returnVal == 0)
        return PointerIsNull;

    rawIgrfMagX = *( (int16_t*) (rxBuffer + 0) );
    returnVal->igrfMagX = rawIgrfMagX*0.01;

    rawIgrfMagY = *( (int16_t*) (rxBuffer + 2) );
    returnVal->igrfMagY = rawIgrfMagY*0.01;

    rawIgrfMagZ = *( (int16_t*) (rxBuffer + 4) );
    returnVal->igrfMagZ = rawIgrfMagZ*0.01;

    rawModelSunX = *( (int16_t*) (rxBuffer + 6) );
    returnVal->modelSunX = rawModelSunX/10000.0;

    rawModelSunY = *( (int16_t*) (rxBuffer + 8) );
    returnVal->modelSunY = rawModelSunY/10000.0;

    rawModelSunZ = *( (int16_t*) (rxBuffer + 10) );
    returnVal->modelSunZ = rawModelSunZ/10000.0;

    rawEstimGyroBiasX = *( (int16_t*) (rxBuffer + 12) );
    returnVal->estimGyroBiasX = rawEstimGyroBiasX*0.001;

    rawEstimGyroBiasY = *( (int16_t*) (rxBuffer + 14) );
    returnVal->estimGyroBiasY = rawEstimGyroBiasY*0.001;

    rawEstimGyroBiasZ = *( (int16_t*) (rxBuffer + 16) );
    returnVal->estimGyroBiasZ = rawEstimGyroBiasZ*0.001;

    rawInnovX = *( (int16_t*) (rxBuffer + 18) );
    returnVal->innovX = rawInnovX*0.0001;

    rawInnovY = *( (int16_t*) (rxBuffer + 20) );
    returnVal->innovY = rawInnovY*0.0001;

    rawInnovZ = *( (int16_t*) (rxBuffer + 22) );
    returnVal->innovZ = rawInnovZ*0.0001;

    rawQError1 = *( (int16_t*) (rxBuffer + 24) );
    returnVal->qError1 = rawQError1*0.0001;

    rawQError2 = *( (int16_t*) (rxBuffer + 26) );
    returnVal->qError2 = rawQError2*0.0001;

    rawQError3 = *( (int16_t*) (rxBuffer + 28) );
    returnVal->qError3 = rawQError3*0.0001;

    rawQCovar1 = *( (int16_t*) (rxBuffer + 30) );
    returnVal->qCovar1 = rawQCovar1*0.001;

    rawQCovar2 = *( (int16_t*) (rxBuffer + 32) );
    returnVal->qCovar2 = rawQCovar2*0.001;

    rawQCovar3 = *( (int16_t*) (rxBuffer + 34) );
    returnVal->qCovar3 = rawQCovar3*0.001;

    rawRateCovarX = *( (int16_t*) (rxBuffer + 36) );
    returnVal->rateCovarX = rawRateCovarX*0.001;

    rawRateCovarY = *( (int16_t*) (rxBuffer + 38) );
    returnVal->rateCovarY = rawRateCovarY*0.001;

    rawRateCovarZ = *( (int16_t*) (rxBuffer + 40) );
    returnVal->rateCovarZ = rawRateCovarZ*0.001;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_EstimGyroBiasTlm(uint8_t* rxBuffer, CUBEACP_EstimGyroBias_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_EstimQuaternionTlm(uint8_t* rxBuffer, CUBEACP_EstimQuaternion_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_EstimRatesTlm(uint8_t* rxBuffer, CUBEACP_EstimRates_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_ExtendedIdentificationTlm(uint8_t* rxBuffer, CUBEACP_ExtendedIdentification_t* returnVal)
{
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    enumVal = (rxBuffer[0] >> 0) & 15;
    returnVal->mcuResetCause = (CUBEACP_ResetCause_t) enumVal;

    enumVal = (rxBuffer[0] >> 4) & 15;
    returnVal->bootCause = (CUBEACP_BootCause_t) enumVal;

    returnVal->bootCounter = *( (uint16_t*) (rxBuffer + 1) );

    enumVal = rxBuffer[3];
    returnVal->runningProgramIndex = (CUBEACP_BootProgramsList_t) enumVal;

    returnVal->firmwareMajorVersion = *( (uint8_t*) (rxBuffer + 4) );

    returnVal->firmwareMinorVersion = *( (uint8_t*) (rxBuffer + 5) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_FileDownloadTlm(uint8_t* rxBuffer, CUBEACP_FileDownload_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->packetNo = *( (uint16_t*) (rxBuffer + 0) );

    memcpy(returnVal->fileBytes, rxBuffer + 2, 20);

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_FileInfoTlm(uint8_t* rxBuffer, CUBEACP_FileInfo_t* returnVal)
{
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    enumVal = (rxBuffer[0] >> 0) & 15;
    returnVal->fileType = (CUBEACP_FileType_t) enumVal;

    returnVal->busyUpdating = (rxBuffer[0] & 0x10) >> 4;

    returnVal->fileCtr = *( (uint8_t*) (rxBuffer + 1) );

    returnVal->size = *( (uint32_t*) (rxBuffer + 2) );

    returnVal->unixTime = *( (uint32_t*) (rxBuffer + 6) );

    returnVal->checksum = *( (uint16_t*) (rxBuffer + 10) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_FineSunVecTlm(uint8_t* rxBuffer, CUBEACP_FineSunVec_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_HoleMap1Tlm(uint8_t* rxBuffer, uint8_t* holeMap)
{
    if (holeMap == 0)
        return PointerIsNull;

    memcpy(holeMap, rxBuffer + 0, 16);

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_HoleMap2Tlm(uint8_t* rxBuffer, uint8_t* holeMap)
{
    if (holeMap == 0)
        return PointerIsNull;

    memcpy(holeMap, rxBuffer + 0, 16);

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_HoleMap3Tlm(uint8_t* rxBuffer, uint8_t* holeMap)
{
    if (holeMap == 0)
        return PointerIsNull;

    memcpy(holeMap, rxBuffer + 0, 16);

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_HoleMap4Tlm(uint8_t* rxBuffer, uint8_t* holeMap)
{
    if (holeMap == 0)
        return PointerIsNull;

    memcpy(holeMap, rxBuffer + 0, 16);

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_HoleMap5Tlm(uint8_t* rxBuffer, uint8_t* holeMap)
{
    if (holeMap == 0)
        return PointerIsNull;

    memcpy(holeMap, rxBuffer + 0, 16);

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_HoleMap6Tlm(uint8_t* rxBuffer, uint8_t* holeMap)
{
    if (holeMap == 0)
        return PointerIsNull;

    memcpy(holeMap, rxBuffer + 0, 16);

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_HoleMap7Tlm(uint8_t* rxBuffer, uint8_t* holeMap)
{
    if (holeMap == 0)
        return PointerIsNull;

    memcpy(holeMap, rxBuffer + 0, 16);

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_HoleMap8Tlm(uint8_t* rxBuffer, uint8_t* holeMap)
{
    if (holeMap == 0)
        return PointerIsNull;

    memcpy(holeMap, rxBuffer + 0, 16);

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_IdentificationTlm(uint8_t* rxBuffer, CUBEACP_Identification_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->nodeType = *( (uint8_t*) (rxBuffer + 0) );

    returnVal->interfaceVersion = *( (uint8_t*) (rxBuffer + 1) );

    returnVal->firmwareMajorVersion = *( (uint8_t*) (rxBuffer + 2) );

    returnVal->firmwareMinorVersion = *( (uint8_t*) (rxBuffer + 3) );

    returnVal->runtimeSeconds = *( (uint16_t*) (rxBuffer + 4) );

    returnVal->runtimeMilliseconds = *( (uint16_t*) (rxBuffer + 6) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_ImageSaveStatusTlm(uint8_t* rxBuffer, CUBEACP_ImageSaveStatus_t* returnVal)
{
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    returnVal->percentageComplete = *( (uint8_t*) (rxBuffer + 0) );

    enumVal = rxBuffer[1];
    returnVal->status = (CUBEACP_ImSaveStatus_t) enumVal;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_InitializeUploadCompleteTlm(uint8_t* rxBuffer, bool* busy)
{
    if (busy == 0)
        return PointerIsNull;

    *busy = (rxBuffer[0] & 0x01) >> 0;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_InnovationVecTlm(uint8_t* rxBuffer, CUBEACP_InnovationVec_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_LastLogEventTlm(uint8_t* rxBuffer, CUBEACP_LastLogEvent_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->unixTime = *( (uint32_t*) (rxBuffer + 0) );

    returnVal->eventId = *( (uint8_t*) (rxBuffer + 4) );

    returnVal->eventParam = *( (uint8_t*) (rxBuffer + 5) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_LatchupErrorsTlm(uint8_t* rxBuffer, CUBEACP_LatchupErrors_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->sRAM1SELs = *( (uint16_t*) (rxBuffer + 0) );

    returnVal->sRAM2SELs = *( (uint16_t*) (rxBuffer + 2) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_LogSdConfig1Tlm(uint8_t* rxBuffer, CUBEACP_LogSdConfig1_t* returnVal)
{
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    memcpy(returnVal->logSelection, rxBuffer + 0, 10);

    returnVal->period = *( (uint16_t*) (rxBuffer + 10) );

    enumVal = rxBuffer[12];
    returnVal->destination = (CUBEACP_SdLogSelect_t) enumVal;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_LogSdConfig2Tlm(uint8_t* rxBuffer, CUBEACP_LogSdConfig2_t* returnVal)
{
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    memcpy(returnVal->logSelection, rxBuffer + 0, 10);

    returnVal->period = *( (uint16_t*) (rxBuffer + 10) );

    enumVal = rxBuffer[12];
    returnVal->destination = (CUBEACP_SdLogSelect_t) enumVal;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_LogUartConfigTlm(uint8_t* rxBuffer, CUBEACP_LogUartConfig_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    memcpy(returnVal->selection, rxBuffer + 0, 10);

    returnVal->period = *( (uint16_t*) (rxBuffer + 10) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_MagFieldTlm(uint8_t* rxBuffer, CUBEACP_MagField_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_MagTorquerCmdTlm(uint8_t* rxBuffer, CUBEACP_MagTorquerCmd_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_ModelMagVecTlm(uint8_t* rxBuffer, CUBEACP_ModelMagVec_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_ModelSunVecTlm(uint8_t* rxBuffer, CUBEACP_ModelSunVec_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_NadirVecTlm(uint8_t* rxBuffer, CUBEACP_NadirVec_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_OrbitParametersTlm(uint8_t* rxBuffer, CUBEACP_OrbitParameters_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    memcpy(&returnVal->inclination, rxBuffer + 0, 8);

    memcpy(&returnVal->eccentricity, rxBuffer + 8, 8);

    memcpy(&returnVal->raan, rxBuffer + 16, 8);

    memcpy(&returnVal->argPerigee, rxBuffer + 24, 8);

    memcpy(&returnVal->bstar, rxBuffer + 32, 8);

    memcpy(&returnVal->meanMotion, rxBuffer + 40, 8);

    memcpy(&returnVal->meanAnomaly, rxBuffer + 48, 8);

    memcpy(&returnVal->epoch, rxBuffer + 56, 8);

    if ((returnVal->inclination < 0) || (returnVal->inclination > 180))
        return TlmRangeError;

    if ((returnVal->eccentricity < 0) || (returnVal->eccentricity > 1))
        return TlmRangeError;

    if ((returnVal->raan < 0) || (returnVal->raan > 360))
        return TlmRangeError;

    if ((returnVal->argPerigee < 0) || (returnVal->argPerigee > 360))
        return TlmRangeError;

    if ((returnVal->bstar < 0) || (returnVal->bstar > 1))
        return TlmRangeError;

    if ((returnVal->meanMotion < 0) || (returnVal->meanMotion > 20))
        return TlmRangeError;

    if ((returnVal->meanAnomaly < 0) || (returnVal->meanAnomaly > 360))
        return TlmRangeError;

    if ((returnVal->epoch < 0) || (returnVal->epoch > 100000))
        return TlmRangeError;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_PositionECEFTlm(uint8_t* rxBuffer, CUBEACP_PositionECEF_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_PositionECITlm(uint8_t* rxBuffer, CUBEACP_PositionECI_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_PositionLLHTlm(uint8_t* rxBuffer, CUBEACP_PositionLLH_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_QuaternionCovarTlm(uint8_t* rxBuffer, CUBEACP_QuaternionCovar_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_QuaternionErrVecTlm(uint8_t* rxBuffer, CUBEACP_QuaternionErrVec_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RateCovarTlm(uint8_t* rxBuffer, CUBEACP_RateCovar_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RateSensorTlm(uint8_t* rxBuffer, CUBEACP_RateSensor_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RawCam1SensTlm(uint8_t* rxBuffer, CUBEACP_RawCam1Sens_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RawCam2SensTlm(uint8_t* rxBuffer, CUBEACP_RawCam2Sens_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RawCss1Tlm(uint8_t* rxBuffer, CUBEACP_RawCss1_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RawCss2Tlm(uint8_t* rxBuffer, CUBEACP_RawCss2_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RawGPSTlm(uint8_t* rxBuffer, CUBEACP_RawGPS_t* returnVal)
{
    uint8_t rawStdDevPosX;
    uint8_t rawStdDevPosY;
    uint8_t rawStdDevPosZ;
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    enumVal = rxBuffer[0];
    returnVal->gpsSolutionStatus = (CUBEACP_GpsSolutionStatus_t) enumVal;

    returnVal->gpsNumSatsTracked = *( (uint8_t*) (rxBuffer + 1) );

    returnVal->gpsNumSatsSolution = *( (uint8_t*) (rxBuffer + 2) );

    returnVal->gpsXYZLogCtr = *( (uint8_t*) (rxBuffer + 3) );

    returnVal->gpsRangeLogCtr = *( (uint8_t*) (rxBuffer + 4) );

    returnVal->gpsResponse = *( (uint8_t*) (rxBuffer + 5) );

    returnVal->gpsWeek = *( (uint16_t*) (rxBuffer + 6) );

    returnVal->gpsTimeMs = *( (uint32_t*) (rxBuffer + 8) );

    returnVal->posEcefX = *( (int32_t*) (rxBuffer + 12) );

    returnVal->velEcefX = *( (int16_t*) (rxBuffer + 16) );

    returnVal->posEcefY = *( (int32_t*) (rxBuffer + 18) );

    returnVal->velEcefY = *( (int16_t*) (rxBuffer + 22) );

    returnVal->posEcefZ = *( (int32_t*) (rxBuffer + 24) );

    returnVal->velEcefZ = *( (int16_t*) (rxBuffer + 28) );

    rawStdDevPosX = *( (uint8_t*) (rxBuffer + 30) );
    returnVal->stdDevPosX = rawStdDevPosX*0.1;

    rawStdDevPosY = *( (uint8_t*) (rxBuffer + 31) );
    returnVal->stdDevPosY = rawStdDevPosY*0.1;

    rawStdDevPosZ = *( (uint8_t*) (rxBuffer + 32) );
    returnVal->stdDevPosZ = rawStdDevPosZ*0.1;

    returnVal->stdDevVelX = *( (uint8_t*) (rxBuffer + 33) );

    returnVal->stdDevVelY = *( (uint8_t*) (rxBuffer + 34) );

    returnVal->stdDevVelZ = *( (uint8_t*) (rxBuffer + 35) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RawGpsStatusTlm(uint8_t* rxBuffer, CUBEACP_RawGpsStatus_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RawGpsTimeTlm(uint8_t* rxBuffer, CUBEACP_RawGpsTime_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RawGpsXTlm(uint8_t* rxBuffer, CUBEACP_RawGpsX_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RawGpsYTlm(uint8_t* rxBuffer, CUBEACP_RawGpsY_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RawGpsZTlm(uint8_t* rxBuffer, CUBEACP_RawGpsZ_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RawMagnetometerTlm(uint8_t* rxBuffer, CUBEACP_RawMagnetometer_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RawSensorTlm(uint8_t* rxBuffer, CUBEACP_RawSensor_t* returnVal)
{
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    returnVal->cam2RawX = *( (int16_t*) (rxBuffer + 0) );

    returnVal->cam2RawY = *( (int16_t*) (rxBuffer + 2) );

    enumVal = rxBuffer[4];
    returnVal->cam2Busy = (CUBEACP_CaptureResult_t) enumVal;

    enumVal = rxBuffer[5];
    returnVal->cam2Result = (CUBEACP_DetectResult_t) enumVal;

    returnVal->cam1RawX = *( (int16_t*) (rxBuffer + 6) );

    returnVal->cam1RawY = *( (int16_t*) (rxBuffer + 8) );

    enumVal = rxBuffer[10];
    returnVal->cam1Busy = (CUBEACP_CaptureResult_t) enumVal;

    enumVal = rxBuffer[11];
    returnVal->cam1Result = (CUBEACP_DetectResult_t) enumVal;

    returnVal->cssRaw1 = *( (uint8_t*) (rxBuffer + 12) );

    returnVal->cssRaw2 = *( (uint8_t*) (rxBuffer + 13) );

    returnVal->cssRaw3 = *( (uint8_t*) (rxBuffer + 14) );

    returnVal->cssRaw4 = *( (uint8_t*) (rxBuffer + 15) );

    returnVal->cssRaw5 = *( (uint8_t*) (rxBuffer + 16) );

    returnVal->cssRaw6 = *( (uint8_t*) (rxBuffer + 17) );

    returnVal->cssRaw7 = *( (uint8_t*) (rxBuffer + 18) );

    returnVal->cssRaw8 = *( (uint8_t*) (rxBuffer + 19) );

    returnVal->cssRaw9 = *( (uint8_t*) (rxBuffer + 20) );

    returnVal->cssRaw10 = *( (uint8_t*) (rxBuffer + 21) );

    returnVal->magRawX = *( (int16_t*) (rxBuffer + 22) );

    returnVal->magRawY = *( (int16_t*) (rxBuffer + 24) );

    returnVal->magRawZ = *( (int16_t*) (rxBuffer + 26) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_RawStarTrackerTlm(uint8_t* rxBuffer, CUBEACP_RawStarTracker_t* returnVal)
{
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    enumVal = (rxBuffer[0] >> 0) & 15;
    returnVal->numStarDetected = (CUBEACP_Stars_t) enumVal;

    enumVal = (rxBuffer[0] >> 4) & 15;
    returnVal->numStarIdent = (CUBEACP_Stars_t) enumVal;

    returnVal->starNoise = *( (uint8_t*) (rxBuffer + 1) );

    returnVal->attitudeSuccess = (rxBuffer[2] & 0x01) >> 0;

    returnVal->imageCaptureSuccess = (rxBuffer[2] & 0x02) >> 1;

    returnVal->detectionSuccess = (rxBuffer[2] & 0x04) >> 2;

    returnVal->identificationSuccess = (rxBuffer[2] & 0x08) >> 3;

    returnVal->loopTimeError = (rxBuffer[2] & 0x10) >> 4;

    returnVal->maxStarsDetected = (rxBuffer[2] & 0x20) >> 5;

    returnVal->lessThanThreeStarsInFoV = (rxBuffer[2] & 0x40) >> 6;

    returnVal->commsError = (rxBuffer[2] & 0x80) >> 7;

    returnVal->confStar1 = *( (uint8_t*) (rxBuffer + 3) );

    returnVal->confStar2 = *( (uint8_t*) (rxBuffer + 4) );

    returnVal->confStar3 = *( (uint8_t*) (rxBuffer + 5) );

    returnVal->magStar1 = *( (uint16_t*) (rxBuffer + 6) );

    returnVal->magStar2 = *( (uint16_t*) (rxBuffer + 8) );

    returnVal->magStar3 = *( (uint16_t*) (rxBuffer + 10) );

    returnVal->catStar1 = *( (uint16_t*) (rxBuffer + 12) );

    returnVal->centXStar1 = *( (int16_t*) (rxBuffer + 14) );

    returnVal->centYStar1 = *( (int16_t*) (rxBuffer + 16) );

    returnVal->catStar2 = *( (uint16_t*) (rxBuffer + 18) );

    returnVal->centXStar2 = *( (int16_t*) (rxBuffer + 20) );

    returnVal->centYStar2 = *( (int16_t*) (rxBuffer + 22) );

    returnVal->catStar3 = *( (uint16_t*) (rxBuffer + 24) );

    returnVal->centXStar3 = *( (int16_t*) (rxBuffer + 26) );

    returnVal->centYStar3 = *( (int16_t*) (rxBuffer + 28) );

    returnVal->capture = *( (uint16_t*) (rxBuffer + 30) );

    returnVal->detection = *( (uint16_t*) (rxBuffer + 32) );

    returnVal->identification = *( (uint16_t*) (rxBuffer + 34) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_ReduntMagRawTlm(uint8_t* rxBuffer, CUBEACP_ReduntMagRaw_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->magRawX = *( (int16_t*) (rxBuffer + 0) );

    returnVal->magRawY = *( (int16_t*) (rxBuffer + 2) );

    returnVal->magRawZ = *( (int16_t*) (rxBuffer + 4) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_SpeedCmdTlm(uint8_t* rxBuffer, CUBEACP_SpeedCmd_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_SramScrubSettingsTlm(uint8_t* rxBuffer, uint16_t* scrubSize)
{
    if (scrubSize == 0)
        return PointerIsNull;

    *scrubSize = *( (uint16_t*) (rxBuffer + 0) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_Star1BodyTlm(uint8_t* rxBuffer, CUBEACP_Star1Body_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_Star1OrbitTlm(uint8_t* rxBuffer, CUBEACP_Star1Orbit_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_Star1RawTlm(uint8_t* rxBuffer, CUBEACP_Star1Raw_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_Star2BodyTlm(uint8_t* rxBuffer, CUBEACP_Star2Body_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_Star2OrbitTlm(uint8_t* rxBuffer, CUBEACP_Star2Orbit_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_Star2RawTlm(uint8_t* rxBuffer, CUBEACP_Star2Raw_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_Star3BodyTlm(uint8_t* rxBuffer, CUBEACP_Star3Body_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_Star3OrbitTlm(uint8_t* rxBuffer, CUBEACP_Star3Orbit_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_Star3RawTlm(uint8_t* rxBuffer, CUBEACP_Star3Raw_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_StarMagnitudeTlm(uint8_t* rxBuffer, CUBEACP_StarMagnitude_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_StarPerformanceTlm(uint8_t* rxBuffer, CUBEACP_StarPerformance_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_StarTimingTlm(uint8_t* rxBuffer, CUBEACP_StarTiming_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_TelecommandAcknowledgeTlm(uint8_t* rxBuffer, CUBEACP_TelecommandAcknowledge_t* returnVal)
{
    uint8_t enumVal;

    if (returnVal == 0)
        return PointerIsNull;

    returnVal->lastTCID = *( (uint8_t*) (rxBuffer + 0) );

    returnVal->processedFlag = (rxBuffer[1] & 0x01) >> 0;

    enumVal = rxBuffer[2];
    returnVal->tCerrorStatus  = (CUBEACP_TcErrorReason_t) enumVal;

    returnVal->tCParameterErrorIndex = *( (uint8_t*) (rxBuffer + 3) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_UnixTimeTlm(uint8_t* rxBuffer, CUBEACP_UnixTime_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->time = *( (uint32_t*) (rxBuffer + 0) );

    returnVal->milliSec = *( (uint16_t*) (rxBuffer + 4) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_UnixTimeSaveTlm(uint8_t* rxBuffer, CUBEACP_UnixTimeSave_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->saveNow = (rxBuffer[0] & 0x01) >> 0;

    returnVal->saveOnUpdate = (rxBuffer[0] & 0x02) >> 1;

    returnVal->savePeriodic = (rxBuffer[0] & 0x04) >> 2;

    returnVal->period = *( (uint8_t*) (rxBuffer + 1) );

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_UploadBlockCompleteTlm(uint8_t* rxBuffer, CUBEACP_UploadBlockComplete_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    returnVal->busy = (rxBuffer[0] & 0x01) >> 0;

    returnVal->error = (rxBuffer[0] & 0x02) >> 1;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_VelocityECITlm(uint8_t* rxBuffer, CUBEACP_VelocityECI_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_WheelCurrentsTlm(uint8_t* rxBuffer, CUBEACP_WheelCurrents_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}

CUBELIB_Result_t CUBEACP_WheelSpeedTlm(uint8_t* rxBuffer, CUBEACP_WheelSpeed_t* returnVal)
{
    if (returnVal == 0)
        return PointerIsNull;

    return CubeLibOk;
}


uint16_t CUBEACP_AdcsConfigCmd(uint8_t* tcBuffer, CUBEACP_AdcsConfig_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 20;

    tcBuffer[1] = 
        (setVal->magtorq1 << 0);
    tcBuffer[2] = 
        (setVal->magtorq2 << 0);
    tcBuffer[3] = 
        (setVal->magtorq3 << 0);
    tcBuffer[4] = 
        (setVal->rW1Conf << 0);
    tcBuffer[5] = 
        (setVal->rW2Conf << 0);
    tcBuffer[6] = 
        (setVal->rW3Conf << 0);
    tcBuffer[7] = 
        (setVal->rW4Conf << 0);
    tcBuffer[8] = 
        (setVal->gyro1Conf << 0);
    tcBuffer[9] = 
        (setVal->gyro2Conf << 0);
    tcBuffer[10] = 
        (setVal->gyro3Conf << 0);
    tcBuffer[11] = 
        (setVal->css1Conf << 0);
    tcBuffer[12] = 
        (setVal->css2Conf << 0);
    tcBuffer[13] = 
        (setVal->css3Conf << 0);
    tcBuffer[14] = 
        (setVal->css4Conf << 0);
    tcBuffer[15] = 
        (setVal->css5Conf << 0);
    tcBuffer[16] = 
        (setVal->css6Conf << 0);
    tcBuffer[17] = 
        (setVal->css7Conf << 0);
    tcBuffer[18] = 
        (setVal->css8Conf << 0);
    tcBuffer[19] = 
        (setVal->css9Conf << 0);
    tcBuffer[20] = 
        (setVal->css10Conf << 0);
    tcBuffer[39] = 
        (setVal->cam1AutoAdj << 0);
    tcBuffer[46] = 
        (setVal->cam1Shift << 0);
    tcBuffer[54] = 
        (setVal->cam2AutoAdj << 0);
    tcBuffer[61] = 
        (setVal->cam2Shift << 0);
    tcBuffer[271] = 
        (setVal->useSunEst << 0) + 
        (setVal->useNadirEst << 1) + 
        (setVal->useCssEst << 2) + 
        (setVal->useStarEst << 3) + 
        (setVal->magMode << 4);
    *( (uint8_t*)(tcBuffer + 21) ) = (uint8_t) round(setVal->css1Scale*100.0);
    *( (uint8_t*)(tcBuffer + 22) ) = (uint8_t) round(setVal->css2Scale*100.0);
    *( (uint8_t*)(tcBuffer + 23) ) = (uint8_t) round(setVal->css3Scale*100.0);
    *( (uint8_t*)(tcBuffer + 24) ) = (uint8_t) round(setVal->css4Scale*100.0);
    *( (uint8_t*)(tcBuffer + 25) ) = (uint8_t) round(setVal->css5Scale*100.0);
    *( (uint8_t*)(tcBuffer + 26) ) = (uint8_t) round(setVal->css6Scale*100.0);
    *( (uint8_t*)(tcBuffer + 27) ) = (uint8_t) round(setVal->css7Scale*100.0);
    *( (uint8_t*)(tcBuffer + 28) ) = (uint8_t) round(setVal->css8Scale*100.0);
    *( (uint8_t*)(tcBuffer + 29) ) = (uint8_t) round(setVal->css9Scale*100.0);
    *( (uint8_t*)(tcBuffer + 30) ) = (uint8_t) round(setVal->css10Scale*100.0);
    *( (uint8_t*)(tcBuffer + 31) ) = setVal->cssMinimum;
    *( (int16_t*)(tcBuffer + 32) ) = (int16_t) round(setVal->cam1Angle1*100.0);
    *( (int16_t*)(tcBuffer + 34) ) = (int16_t) round(setVal->cam1Angle2*100.0);
    *( (int16_t*)(tcBuffer + 36) ) = (int16_t) round(setVal->cam1Angle3*100.0);
    *( (uint8_t*)(tcBuffer + 38) ) = setVal->cam1Threshold;
    *( (uint16_t*)(tcBuffer + 40) ) = setVal->cam1Exposure;
    *( (uint16_t*)(tcBuffer + 42) ) = (uint16_t) round(setVal->cam1BoreX*100.0);
    *( (uint16_t*)(tcBuffer + 44) ) = (uint16_t) round(setVal->cam1BoreY*100.0);
    *( (int16_t*)(tcBuffer + 47) ) = (int16_t) round(setVal->cam2Angle1*100.0);
    *( (int16_t*)(tcBuffer + 49) ) = (int16_t) round(setVal->cam2Angle2*100.0);
    *( (int16_t*)(tcBuffer + 51) ) = (int16_t) round(setVal->cam2Angle3*100.0);
    *( (uint8_t*)(tcBuffer + 53) ) = setVal->cam2Threshold;
    *( (uint16_t*)(tcBuffer + 55) ) = setVal->cam2Exposure;
    *( (uint16_t*)(tcBuffer + 57) ) = (uint16_t) round(setVal->cam2BoreX*100.0);
    *( (uint16_t*)(tcBuffer + 59) ) = (uint16_t) round(setVal->cam2BoreY*100.0);
    *( (uint16_t*)(tcBuffer + 62) ) = setVal->maskArea1Xmin;
    *( (uint16_t*)(tcBuffer + 64) ) = setVal->maskArea1Xmax;
    *( (uint16_t*)(tcBuffer + 66) ) = setVal->maskArea1Ymin;
    *( (uint16_t*)(tcBuffer + 68) ) = setVal->maskArea1Ymax;
    *( (uint16_t*)(tcBuffer + 70) ) = setVal->maskArea2Xmin;
    *( (uint16_t*)(tcBuffer + 72) ) = setVal->maskArea2Xmax;
    *( (uint16_t*)(tcBuffer + 74) ) = setVal->maskArea2Ymin;
    *( (uint16_t*)(tcBuffer + 76) ) = setVal->maskArea2Ymax;
    *( (uint16_t*)(tcBuffer + 78) ) = setVal->maskArea3Xmin;
    *( (uint16_t*)(tcBuffer + 80) ) = setVal->maskArea3Xmax;
    *( (uint16_t*)(tcBuffer + 82) ) = setVal->maskArea3Ymin;
    *( (uint16_t*)(tcBuffer + 84) ) = setVal->maskArea3Ymax;
    *( (uint16_t*)(tcBuffer + 86) ) = setVal->maskArea4Xmin;
    *( (uint16_t*)(tcBuffer + 88) ) = setVal->maskArea4Xmax;
    *( (uint16_t*)(tcBuffer + 90) ) = setVal->maskArea4Ymin;
    *( (uint16_t*)(tcBuffer + 92) ) = setVal->maskArea4Ymax;
    *( (uint16_t*)(tcBuffer + 94) ) = setVal->maskArea5Xmin;
    *( (uint16_t*)(tcBuffer + 96) ) = setVal->maskArea5Xmax;
    *( (uint16_t*)(tcBuffer + 98) ) = setVal->maskArea5Ymin;
    *( (uint16_t*)(tcBuffer + 100) ) = setVal->maskArea5Ymax;
    *( (int16_t*)(tcBuffer + 102) ) = (int16_t) round(setVal->magmAngle1*100.0);
    *( (int16_t*)(tcBuffer + 104) ) = (int16_t) round(setVal->magmAngle2*100.0);
    *( (int16_t*)(tcBuffer + 106) ) = (int16_t) round(setVal->magmAngle3*100.0);
    *( (int16_t*)(tcBuffer + 108) ) = (int16_t) round(setVal->magmOffset1*1000.0);
    *( (int16_t*)(tcBuffer + 110) ) = (int16_t) round(setVal->magmOffset2*1000.0);
    *( (int16_t*)(tcBuffer + 112) ) = (int16_t) round(setVal->magmOffset3*1000.0);
    *( (int16_t*)(tcBuffer + 114) ) = (int16_t) round(setVal->magmSens11*1000.0);
    *( (int16_t*)(tcBuffer + 116) ) = (int16_t) round(setVal->magmSens22*1000.0);
    *( (int16_t*)(tcBuffer + 118) ) = (int16_t) round(setVal->magmSens33*1000.0);
    *( (int16_t*)(tcBuffer + 120) ) = (int16_t) round(setVal->magmSens12*1000.0);
    *( (int16_t*)(tcBuffer + 122) ) = (int16_t) round(setVal->magmSens13*1000.0);
    *( (int16_t*)(tcBuffer + 124) ) = (int16_t) round(setVal->magmSens21*1000.0);
    *( (int16_t*)(tcBuffer + 126) ) = (int16_t) round(setVal->magmSens23*1000.0);
    *( (int16_t*)(tcBuffer + 128) ) = (int16_t) round(setVal->magmSens31*1000.0);
    *( (int16_t*)(tcBuffer + 130) ) = (int16_t) round(setVal->magmSens32*1000.0);
    *( (int16_t*)(tcBuffer + 132) ) = (int16_t) round(setVal->xRateOffset*1000.0);
    *( (int16_t*)(tcBuffer + 134) ) = (int16_t) round(setVal->yRateOffset*1000.0);
    *( (int16_t*)(tcBuffer + 136) ) = (int16_t) round(setVal->zRateOffset*1000.0);
    *( (uint8_t*)(tcBuffer + 138) ) = setVal->rateSensorMult;
    *( (int16_t*)(tcBuffer + 139) ) = (int16_t) round(setVal->starAngle1*100.0);
    *( (int16_t*)(tcBuffer + 141) ) = (int16_t) round(setVal->starAngle2*100.0);
    *( (int16_t*)(tcBuffer + 143) ) = (int16_t) round(setVal->starAngle3*100.0);
    *( (uint16_t*)(tcBuffer + 145) ) = setVal->starExposure;
    *( (uint8_t*)(tcBuffer + 147) ) = setVal->detectionThreshold;
    *( (uint8_t*)(tcBuffer + 148) ) = setVal->starThreshold;
    *( (uint8_t*)(tcBuffer + 149) ) = setVal->maxStarMatched;
    *( (uint8_t*)(tcBuffer + 150) ) = setVal->maxStarPixel;
    *( (uint8_t*)(tcBuffer + 151) ) = setVal->maxStarNoise;
    *( (uint8_t*)(tcBuffer + 152) ) = setVal->minStarPixel;
    *( (uint8_t*)(tcBuffer + 153) ) = (uint8_t) round(setVal->starErrorMargin*100.0);
    *( (float*)(tcBuffer + 154) ) = setVal->starCentX;
    *( (float*)(tcBuffer + 158) ) = setVal->starCentY;
    *( (uint16_t*)(tcBuffer + 162) ) = (uint16_t) round(setVal->starFocal*10000.0);
    *( (uint8_t*)(tcBuffer + 164) ) = setVal->syncDelay;
    *( (float*)(tcBuffer + 165) ) = setVal->ks;
    *( (float*)(tcBuffer + 169) ) = setVal->kd;
    *( (int16_t*)(tcBuffer + 173) ) = (int16_t) round(setVal->wy_ref*1000.0);
    *( (float*)(tcBuffer + 175) ) = setVal->kdf;
    *( (float*)(tcBuffer + 179) ) = setVal->kh;
    *( (float*)(tcBuffer + 183) ) = setVal->kn;
    *( (float*)(tcBuffer + 187) ) = setVal->kp1;
    *( (float*)(tcBuffer + 191) ) = setVal->kd1;
    *( (float*)(tcBuffer + 195) ) = setVal->h_ref;
    *( (float*)(tcBuffer + 199) ) = setVal->kp2;
    *( (float*)(tcBuffer + 203) ) = setVal->kd2;
    *( (float*)(tcBuffer + 207) ) = setVal->kp3;
    *( (float*)(tcBuffer + 211) ) = setVal->kd3;
    *( (float*)(tcBuffer + 215) ) = setVal->ki3;
    *( (float*)(tcBuffer + 219) ) = setVal->ixx;
    *( (float*)(tcBuffer + 223) ) = setVal->iyy;
    *( (float*)(tcBuffer + 227) ) = setVal->izz;
    *( (float*)(tcBuffer + 231) ) = setVal->ixy;
    *( (float*)(tcBuffer + 235) ) = setVal->ixz;
    *( (float*)(tcBuffer + 239) ) = setVal->iyz;
    *( (float*)(tcBuffer + 243) ) = setVal->magRateNoise;
    *( (float*)(tcBuffer + 247) ) = setVal->ekfSysNoise;
    *( (float*)(tcBuffer + 251) ) = setVal->cssNoise;
    *( (float*)(tcBuffer + 255) ) = setVal->sunNoise;
    *( (float*)(tcBuffer + 259) ) = setVal->nadirNoise;
    *( (float*)(tcBuffer + 263) ) = setVal->magNoise;
    *( (float*)(tcBuffer + 267) ) = setVal->starNoise;
    *( (uint8_t*)(tcBuffer + 272) ) = setVal->cam1Cam2Period;

    return 273;
}

uint16_t CUBEACP_AdcsEnabledCmd(uint8_t* tcBuffer, CUBEACP_AdcsRunMode_t enabled)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 10;

    tcBuffer[1] = 
        (enabled << 0);

    return 2;
}

uint16_t CUBEACP_AdcsPowerCmd(uint8_t* tcBuffer, CUBEACP_AdcsPower_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 11;

    tcBuffer[1] = 
        (setVal->cubeControlSignalPower << 0) + 
        (setVal->cubeControlMotorPower << 2) + 
        (setVal->cubeSensePower << 4) + 
        (setVal->cubeStarPower << 6);
    tcBuffer[2] = 
        (setVal->cubeWheel1Power << 0) + 
        (setVal->cubeWheel2Power << 2) + 
        (setVal->cubeWheel3Power << 4) + 
        (setVal->motorPower << 6);
    tcBuffer[3] = 
        (setVal->gpsLnaPower << 0);

    return 4;
}

uint16_t CUBEACP_AdvanceFileListPtrCmd(uint8_t* tcBuffer)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 113;


    return 1;
}

uint16_t CUBEACP_AdvanceLogPtrCmd(uint8_t* tcBuffer)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 5;


    return 1;
}

uint16_t CUBEACP_CacheCmd(uint8_t* tcBuffer, bool enabled)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 3;

    tcBuffer[1] = 
        (enabled << 0);

    return 2;
}

uint16_t CUBEACP_Cam1ConfigCmd(uint8_t* tcBuffer, CUBEACP_Cam1Config_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 26;


    return 16;
}

uint16_t CUBEACP_Cam2ConfigCmd(uint8_t* tcBuffer, CUBEACP_Cam2Config_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 27;


    return 16;
}

uint16_t CUBEACP_ClearErrorsCmd(uint8_t* tcBuffer, CUBEACP_ClearErrors_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 12;

    tcBuffer[1] = 
        (setVal->aDCSErrors << 0) + 
        (setVal->hKErrors << 1);

    return 2;
}

uint16_t CUBEACP_CmdAttitudeCmd(uint8_t* tcBuffer, CUBEACP_CmdAttitude_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 15;

    *( (int16_t*)(tcBuffer + 1) ) = (int16_t) round(setVal->roll*100.0);
    *( (int16_t*)(tcBuffer + 3) ) = (int16_t) round(setVal->pitch*100.0);
    *( (int16_t*)(tcBuffer + 5) ) = (int16_t) round(setVal->yaw*100.0);

    return 7;
}

uint16_t CUBEACP_CmdTrackingTargetCmd(uint8_t* tcBuffer, float longRef, float latRef, float altRef)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 55;

    *( (float*)(tcBuffer + 1) ) = longRef;
    *( (float*)(tcBuffer + 5) ) = latRef;
    *( (float*)(tcBuffer + 9) ) = altRef;

    return 13;
}

uint16_t CUBEACP_ControlModeCmd(uint8_t* tcBuffer, CUBEACP_ControlMode_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 13;

    tcBuffer[1] = 
        (setVal->controlModeSelection << 0);
    tcBuffer[2] = 
        (setVal->overrideErrors << 0);
    *( (uint16_t*)(tcBuffer + 3) ) = setVal->timeout;

    return 5;
}

uint16_t CUBEACP_ConvertCmd(uint8_t* tcBuffer, uint8_t srcFileCtr, uint8_t qualityFactor, uint8_t whiteBalance)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 57;

    *( (uint8_t*)(tcBuffer + 1) ) = srcFileCtr;
    *( (uint8_t*)(tcBuffer + 2) ) = qualityFactor;
    *( (uint8_t*)(tcBuffer + 3) ) = whiteBalance;

    return 4;
}

uint16_t CUBEACP_CssConfig1Cmd(uint8_t* tcBuffer, CUBEACP_CssConfig1_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 24;


    return 11;
}

uint16_t CUBEACP_CssConfig2Cmd(uint8_t* tcBuffer, CUBEACP_CssConfig2_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 25;


    return 12;
}

uint16_t CUBEACP_DefaultConfigCmd(uint8_t* tcBuffer)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 60;


    return 1;
}

uint16_t CUBEACP_DeployMagnetometerCmd(uint8_t* tcBuffer, uint8_t timeout)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 7;

    *( (uint8_t*)(tcBuffer + 1) ) = timeout;

    return 2;
}

uint16_t CUBEACP_DetumbleParamsCmd(uint8_t* tcBuffer, CUBEACP_DetumbleParams_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 38;


    return 15;
}

uint16_t CUBEACP_DownloadBurstCmd(uint8_t* tcBuffer, uint8_t messageLength, bool ignoreHoleMap)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 119;

    tcBuffer[2] = 
        (ignoreHoleMap << 0);
    *( (uint8_t*)(tcBuffer + 1) ) = messageLength;

    return 3;
}

uint16_t CUBEACP_EraseFileCmd(uint8_t* tcBuffer, CUBEACP_FileType_t fileType, uint8_t fileCtr, bool eraseAll)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 108;

    tcBuffer[1] = 
        (fileType << 0);
    tcBuffer[3] = 
        (eraseAll << 0);
    *( (uint8_t*)(tcBuffer + 2) ) = fileCtr;

    return 4;
}

uint16_t CUBEACP_EstimModeCmd(uint8_t* tcBuffer, CUBEACP_EstimModeSelect_t estimModeSelection)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 14;

    tcBuffer[1] = 
        (setVal->estimModeSelection << 0);

    return 2;
}

uint16_t CUBEACP_EstimParams1Cmd(uint8_t* tcBuffer, CUBEACP_EstimParams1_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 43;


    return 17;
}

uint16_t CUBEACP_EstimParams2Cmd(uint8_t* tcBuffer, CUBEACP_EstimParams2_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 44;


    return 15;
}

uint16_t CUBEACP_FileUploadCmd(uint8_t* tcBuffer, uint16_t packetNo, uint8_t* fileBytes)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 115;

    *( (uint16_t*)(tcBuffer + 1) ) = packetNo;
    memcpy(tcBuffer + 3,fileBytes,20);

    return 23;
}

uint16_t CUBEACP_FinalizeUploadBlockCmd(uint8_t* tcBuffer, CUBEACP_FileUploadDestination_t destination, uint32_t offset, uint16_t blockLen)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 116;

    tcBuffer[1] = 
        (destination << 0);
    *( (uint32_t*)(tcBuffer + 2) ) = offset;
    *( (uint16_t*)(tcBuffer + 6) ) = blockLen;

    return 8;
}

uint16_t CUBEACP_GyroConfigCmd(uint8_t* tcBuffer, CUBEACP_GyroConfig_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 23;


    return 4;
}

uint16_t CUBEACP_HoleMap1Cmd(uint8_t* tcBuffer, uint8_t* holeMap)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 120;

    memcpy(tcBuffer + 1,holeMap,16);

    return 17;
}

uint16_t CUBEACP_HoleMap2Cmd(uint8_t* tcBuffer, uint8_t* holeMap)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 121;

    memcpy(tcBuffer + 1,holeMap,16);

    return 17;
}

uint16_t CUBEACP_HoleMap3Cmd(uint8_t* tcBuffer, uint8_t* holeMap)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 122;

    memcpy(tcBuffer + 1,holeMap,16);

    return 17;
}

uint16_t CUBEACP_HoleMap4Cmd(uint8_t* tcBuffer, uint8_t* holeMap)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 123;

    memcpy(tcBuffer + 1,holeMap,16);

    return 17;
}

uint16_t CUBEACP_HoleMap5Cmd(uint8_t* tcBuffer, uint8_t* holeMap)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 124;

    memcpy(tcBuffer + 1,holeMap,16);

    return 17;
}

uint16_t CUBEACP_HoleMap6Cmd(uint8_t* tcBuffer, uint8_t* holeMap)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 125;

    memcpy(tcBuffer + 1,holeMap,16);

    return 17;
}

uint16_t CUBEACP_HoleMap7Cmd(uint8_t* tcBuffer, uint8_t* holeMap)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 126;

    memcpy(tcBuffer + 1,holeMap,16);

    return 17;
}

uint16_t CUBEACP_HoleMap8Cmd(uint8_t* tcBuffer, uint8_t* holeMap)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 127;

    memcpy(tcBuffer + 1,holeMap,16);

    return 17;
}

uint16_t CUBEACP_InitiateFileUploadCmd(uint8_t* tcBuffer, CUBEACP_FileUploadDestination_t destination, uint8_t blockSize)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 114;

    tcBuffer[1] = 
        (destination << 0);
    *( (uint8_t*)(tcBuffer + 2) ) = blockSize;

    return 3;
}

uint16_t CUBEACP_LoadDownloadBlockCmd(uint8_t* tcBuffer, CUBEACP_FileType_t fileType, uint8_t counter, uint32_t offset, uint16_t length)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 112;

    tcBuffer[1] = 
        (fileType << 0);
    *( (uint8_t*)(tcBuffer + 2) ) = counter;
    *( (uint32_t*)(tcBuffer + 3) ) = offset;
    *( (uint16_t*)(tcBuffer + 7) ) = length;

    return 9;
}

uint16_t CUBEACP_LogSdConfig1Cmd(uint8_t* tcBuffer, uint8_t* logSelection, uint16_t period, CUBEACP_SdLogSelect_t destination)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 104;

    tcBuffer[13] = 
        (destination << 0);
    memcpy(tcBuffer + 1,logSelection,10);
    *( (uint16_t*)(tcBuffer + 11) ) = period;

    return 14;
}

uint16_t CUBEACP_LogSdConfig2Cmd(uint8_t* tcBuffer, uint8_t* logSelection, uint16_t period, CUBEACP_SdLogSelect_t destination)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 105;

    tcBuffer[13] = 
        (destination << 0);
    memcpy(tcBuffer + 1,logSelection,10);
    *( (uint16_t*)(tcBuffer + 11) ) = period;

    return 14;
}

uint16_t CUBEACP_LogUartConfigCmd(uint8_t* tcBuffer, uint8_t* selection, uint16_t period)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 106;

    memcpy(tcBuffer + 1,selection,10);
    *( (uint16_t*)(tcBuffer + 11) ) = period;

    return 13;
}

uint16_t CUBEACP_MagConfig1Cmd(uint8_t* tcBuffer, CUBEACP_MagConfig1_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 33;


    return 7;
}

uint16_t CUBEACP_MagConfig2Cmd(uint8_t* tcBuffer, CUBEACP_MagConfig2_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 34;


    return 13;
}

uint16_t CUBEACP_MagConfig3Cmd(uint8_t* tcBuffer, CUBEACP_MagConfig3_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 35;


    return 13;
}

uint16_t CUBEACP_MagModeCmd(uint8_t* tcBuffer, CUBEACP_MagModeVal_t modeSetting)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 56;

    tcBuffer[1] = 
        (modeSetting << 0);

    return 2;
}

uint16_t CUBEACP_MagtorqConfigCmd(uint8_t* tcBuffer, CUBEACP_MagtorqConfig_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 21;


    return 4;
}

uint16_t CUBEACP_MoICmd(uint8_t* tcBuffer, CUBEACP_MoI_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 41;


    return 13;
}

uint16_t CUBEACP_NadirMaskConfig1Cmd(uint8_t* tcBuffer, CUBEACP_NadirMaskConfig1_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 28;


    return 9;
}

uint16_t CUBEACP_NadirMaskConfig2Cmd(uint8_t* tcBuffer, CUBEACP_NadirMaskConfig2_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 29;


    return 9;
}

uint16_t CUBEACP_NadirMaskConfig3Cmd(uint8_t* tcBuffer, CUBEACP_NadirMaskConfig3_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 30;


    return 9;
}

uint16_t CUBEACP_NadirMaskConfig4Cmd(uint8_t* tcBuffer, CUBEACP_NadirMaskConfig4_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 31;


    return 9;
}

uint16_t CUBEACP_NadirMaskConfig5Cmd(uint8_t* tcBuffer, CUBEACP_NadirMaskConfig5_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 32;


    return 9;
}

uint16_t CUBEACP_OrbitArgPerCmd(uint8_t* tcBuffer, CUBEACP_OrbitArgPer_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 49;


    return 9;
}

uint16_t CUBEACP_OrbitBStarCmd(uint8_t* tcBuffer, CUBEACP_OrbitBStar_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 50;


    return 9;
}

uint16_t CUBEACP_OrbitEccentricityCmd(uint8_t* tcBuffer, CUBEACP_OrbitEccentricity_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 47;


    return 9;
}

uint16_t CUBEACP_OrbitEpochCmd(uint8_t* tcBuffer, CUBEACP_OrbitEpoch_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 53;


    return 9;
}

uint16_t CUBEACP_OrbitInclinationCmd(uint8_t* tcBuffer, CUBEACP_OrbitInclination_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 46;


    return 9;
}

uint16_t CUBEACP_OrbitMeanAnomCmd(uint8_t* tcBuffer, CUBEACP_OrbitMeanAnom_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 52;


    return 9;
}

uint16_t CUBEACP_OrbitMeanMotCmd(uint8_t* tcBuffer, CUBEACP_OrbitMeanMot_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 51;


    return 9;
}

uint16_t CUBEACP_OrbitParametersCmd(uint8_t* tcBuffer, CUBEACP_OrbitParameters_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 45;

    memcpy(tcBuffer + 1, &setVal->inclination, 8);
    memcpy(tcBuffer + 9, &setVal->eccentricity, 8);
    memcpy(tcBuffer + 17, &setVal->raan, 8);
    memcpy(tcBuffer + 25, &setVal->argPerigee, 8);
    memcpy(tcBuffer + 33, &setVal->bstar, 8);
    memcpy(tcBuffer + 41, &setVal->meanMotion, 8);
    memcpy(tcBuffer + 49, &setVal->meanAnomaly, 8);
    memcpy(tcBuffer + 57, &setVal->epoch, 8);

    return 65;
}

uint16_t CUBEACP_OrbitRaanCmd(uint8_t* tcBuffer, CUBEACP_OrbitRaan_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 48;


    return 9;
}

uint16_t CUBEACP_PoICmd(uint8_t* tcBuffer, CUBEACP_PoI_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 42;


    return 13;
}

uint16_t CUBEACP_RateConfigCmd(uint8_t* tcBuffer, CUBEACP_RateConfig_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 36;


    return 8;
}

uint16_t CUBEACP_ResetCmd(uint8_t* tcBuffer, uint8_t magic)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 1;

    *( (uint8_t*)(tcBuffer + 1) ) = magic;

    return 2;
}

uint16_t CUBEACP_ResetBootRegistersCmd(uint8_t* tcBuffer)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 6;


    return 1;
}

uint16_t CUBEACP_ResetFileListPtrCmd(uint8_t* tcBuffer)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 118;


    return 1;
}

uint16_t CUBEACP_ResetLogPtrCmd(uint8_t* tcBuffer)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 4;


    return 1;
}

uint16_t CUBEACP_ResetUploadBlockCmd(uint8_t* tcBuffer)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 117;


    return 1;
}

uint16_t CUBEACP_RWheelParamsCmd(uint8_t* tcBuffer, CUBEACP_RWheelParams_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 40;


    return 9;
}

uint16_t CUBEACP_SaveConfigCmd(uint8_t* tcBuffer)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 63;


    return 1;
}

uint16_t CUBEACP_SaveImageCmd(uint8_t* tcBuffer, CUBEACP_SaveImage_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 80;

    tcBuffer[1] = 
        (setVal->cameraSelect << 0);
    tcBuffer[2] = 
        (setVal->imageSize << 0);

    return 3;
}

uint16_t CUBEACP_SaveOrbitParamsCmd(uint8_t* tcBuffer)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 64;


    return 1;
}

uint16_t CUBEACP_SramScrubSettingsCmd(uint8_t* tcBuffer, uint16_t scrubSize)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 8;

    *( (uint16_t*)(tcBuffer + 1) ) = scrubSize;

    return 3;
}

uint16_t CUBEACP_StarConfigCmd(uint8_t* tcBuffer, CUBEACP_StarConfig_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 37;


    return 27;
}

uint16_t CUBEACP_TorquerCmdCmd(uint8_t* tcBuffer, CUBEACP_TorquerCmd_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 16;

    *( (int16_t*)(tcBuffer + 1) ) = (int16_t) round(setVal->torquerX*1000.0);
    *( (int16_t*)(tcBuffer + 3) ) = (int16_t) round(setVal->torquerY*1000.0);
    *( (int16_t*)(tcBuffer + 5) ) = (int16_t) round(setVal->torquerZ*1000.0);

    return 7;
}

uint16_t CUBEACP_TrackingParamsCmd(uint8_t* tcBuffer, CUBEACP_TrackingParams_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 54;


    return 13;
}

uint16_t CUBEACP_TriggerAdcsCmd(uint8_t* tcBuffer, CUBEACP_TriggerAdcs_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 18;


    return 1;
}

uint16_t CUBEACP_TriggerAdcsSensorCmd(uint8_t* tcBuffer, CUBEACP_TriggerAdcsSensor_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 19;

    *( (uint32_t*)(tcBuffer + 1) ) = setVal->unixTime;
    *( (uint16_t*)(tcBuffer + 5) ) = setVal->cssRaw1;
    *( (uint16_t*)(tcBuffer + 7) ) = setVal->cssRaw2;
    *( (uint16_t*)(tcBuffer + 9) ) = setVal->cssRaw3;
    *( (uint16_t*)(tcBuffer + 11) ) = setVal->cssRaw4;
    *( (uint16_t*)(tcBuffer + 13) ) = setVal->cssRaw5;
    *( (uint16_t*)(tcBuffer + 15) ) = setVal->cssRaw6;
    *( (uint16_t*)(tcBuffer + 17) ) = setVal->cssRaw7;
    *( (uint16_t*)(tcBuffer + 19) ) = setVal->cssRaw8;
    *( (uint16_t*)(tcBuffer + 21) ) = setVal->cssRaw9;
    *( (uint16_t*)(tcBuffer + 23) ) = setVal->cssRaw10;
    *( (int16_t*)(tcBuffer + 25) ) = setVal->cam1RawX;
    *( (int16_t*)(tcBuffer + 27) ) = setVal->cam1RawY;
    *( (uint8_t*)(tcBuffer + 29) ) = setVal->cam1Busy;
    *( (uint8_t*)(tcBuffer + 30) ) = setVal->cam1Result;
    *( (int16_t*)(tcBuffer + 31) ) = setVal->cam2RawX;
    *( (int16_t*)(tcBuffer + 33) ) = setVal->cam2RawY;
    *( (uint8_t*)(tcBuffer + 35) ) = setVal->cam2Busy;
    *( (uint8_t*)(tcBuffer + 36) ) = setVal->cam2Result;
    *( (int16_t*)(tcBuffer + 37) ) = setVal->magRawX;
    *( (int16_t*)(tcBuffer + 39) ) = setVal->magRawY;
    *( (int16_t*)(tcBuffer + 41) ) = setVal->magRawZ;
    *( (int16_t*)(tcBuffer + 43) ) = setVal->rateRawX;
    *( (int16_t*)(tcBuffer + 45) ) = setVal->rateRawY;
    *( (int16_t*)(tcBuffer + 47) ) = setVal->rateRawZ;
    *( (int16_t*)(tcBuffer + 49) ) = setVal->wheelRawX;
    *( (int16_t*)(tcBuffer + 51) ) = setVal->wheelRawY;
    *( (int16_t*)(tcBuffer + 53) ) = setVal->wheelRawZ;
    *( (int16_t*)(tcBuffer + 55) ) = setVal->star1CameraX;
    *( (int16_t*)(tcBuffer + 57) ) = setVal->star1CameraY;
    *( (int16_t*)(tcBuffer + 59) ) = setVal->star1CameraZ;
    *( (int16_t*)(tcBuffer + 61) ) = setVal->star1InertialX;
    *( (int16_t*)(tcBuffer + 63) ) = setVal->star1InertialY;
    *( (int16_t*)(tcBuffer + 65) ) = setVal->star1InertialZ;
    *( (int16_t*)(tcBuffer + 67) ) = setVal->star2CameraX;
    *( (int16_t*)(tcBuffer + 69) ) = setVal->star2CameraY;
    *( (int16_t*)(tcBuffer + 71) ) = setVal->star2CameraZ;
    *( (int16_t*)(tcBuffer + 73) ) = setVal->star2InertialX;
    *( (int16_t*)(tcBuffer + 75) ) = setVal->star2InertialY;
    *( (int16_t*)(tcBuffer + 77) ) = setVal->star2InertialZ;
    *( (int16_t*)(tcBuffer + 79) ) = setVal->star3CameraX;
    *( (int16_t*)(tcBuffer + 81) ) = setVal->star3CameraY;
    *( (int16_t*)(tcBuffer + 83) ) = setVal->star3CameraZ;
    *( (int16_t*)(tcBuffer + 85) ) = setVal->star3InertialX;
    *( (int16_t*)(tcBuffer + 87) ) = setVal->star3InertialY;
    *( (int16_t*)(tcBuffer + 89) ) = setVal->star3InertialZ;

    return 91;
}

uint16_t CUBEACP_UnixTimeCmd(uint8_t* tcBuffer, uint32_t time, uint16_t milliSec)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 2;

    *( (uint32_t*)(tcBuffer + 1) ) = time;
    *( (uint16_t*)(tcBuffer + 5) ) = milliSec;

    return 7;
}

uint16_t CUBEACP_UnixTimeSaveCmd(uint8_t* tcBuffer, bool saveNow, bool saveOnUpdate, bool savePeriodic, uint8_t period)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 9;

    tcBuffer[1] = 
        (saveNow << 0) + 
        (saveOnUpdate << 1) + 
        (savePeriodic << 2);
    *( (uint8_t*)(tcBuffer + 2) ) = period;

    return 3;
}

uint16_t CUBEACP_WheelConfigCmd(uint8_t* tcBuffer, CUBEACP_WheelConfig_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 22;


    return 5;
}

uint16_t CUBEACP_WheelSpeedCmdCmd(uint8_t* tcBuffer, CUBEACP_WheelSpeedCmd_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 17;

    *( (int16_t*)(tcBuffer + 1) ) = setVal->wheelX;
    *( (int16_t*)(tcBuffer + 3) ) = setVal->wheelY;
    *( (int16_t*)(tcBuffer + 5) ) = setVal->wheelZ;

    return 7;
}

uint16_t CUBEACP_YWheelParamsCmd(uint8_t* tcBuffer, CUBEACP_YWheelParams_t* setVal)
{
    // write TtcMessage ID to first element in buffer
    tcBuffer[0] = 39;


    return 21;
}


